// src/components/contact/ContactSection.tsx
import React, { useState } from 'react';
import { sound } from '../../audio/soundEffects';
import confetti from 'canvas-confetti';
import { Send, Mail, MessageSquare, Sparkles, CheckCircle2, Coffee } from 'lucide-react';
import { GithubIcon, LinkedinIcon } from '../ui/Icons';

export const ContactSection: React.FC = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    projectType: 'Full-Stack Web App',
    coffeeOffering: '1 Ly Robusta Đen Đậm Đặc ☕',
    message: '',
  });

  const [submitted, setSubmitted] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.name || !formData.email || !formData.message) return;

    setLoading(true);
    sound.playTalisman();

    setTimeout(() => {
      setLoading(false);
      setSubmitted(true);
      sound.playSuccess();

      confetti({
        particleCount: 80,
        spread: 70,
        origin: { y: 0.6 },
        colors: ['#00f5a0', '#ffd166', '#ff0054', '#00d2ff'],
      });
    }, 600);
  };

  return (
    <section id="contact" className="py-24 relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full glass-panel border border-slate-700 text-xs font-mono text-emerald-300">
            <Mail className="w-3.5 h-3.5 text-talisman-yellow" />
            <span>// SUMMONING ALTAR</span>
          </div>
          <h2 className="font-display font-extrabold text-3xl sm:text-5xl text-white tracking-tight">
            Summon <span className="text-phantom-mint text-glow-mint">Ma Cà Tưng</span>
          </h2>
          <p className="text-slate-400 font-mono text-sm sm:text-base">
            Bạn có ý tưởng dự án tham vọng hoặc muốn đồng hành cùng một kỹ sư tận tâm? Hãy phát tín hiệu triệu hồi ngay!
          </p>
        </div>

        {/* Grid: Contact Form on Left, Direct Channels on Right */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Summoning Form */}
          <div className="lg:col-span-7 rounded-3xl glass-panel-glow border border-emerald-500/30 p-6 sm:p-8 relative">
            
            {submitted ? (
              <div className="py-12 text-center space-y-4 animate-fadeIn">
                <div className="w-16 h-16 rounded-full bg-emerald-500/20 border-2 border-emerald-400 mx-auto flex items-center justify-center text-emerald-300 shadow-glow-mint">
                  <CheckCircle2 className="w-8 h-8" />
                </div>
                <h3 className="font-display font-bold text-2xl text-white">
                  Tín Hiệu Triệu Hồi Đã Được Tiếp Nhận! ⚡
                </h3>
                <p className="text-slate-300 font-mono text-sm max-w-md mx-auto leading-relaxed">
                  Cảm ơn <strong className="text-emerald-300">{formData.name}</strong>. Ma Cà Tưng đã nhận được phong thư cùng lời thỉnh cầu. Tôi sẽ hồi đáp email của bạn ngay trong chu kỳ mặt trăng tiếp theo!
                </p>
                <div className="pt-4">
                  <button
                    onClick={() => {
                      sound.playClick();
                      setSubmitted(false);
                      setFormData({
                        name: '',
                        email: '',
                        projectType: 'Full-Stack Web App',
                        coffeeOffering: '1 Ly Robusta Đen Đậm Đặc ☕',
                        message: '',
                      });
                    }}
                    className="px-5 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-mono text-xs transition-colors"
                  >
                    Gửi thêm một thông điệp khác
                  </button>
                </div>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-5">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  
                  {/* Name */}
                  <div className="space-y-1.5">
                    <label className="text-xs font-mono text-slate-300 font-bold">
                      Tên của bạn / Tổ chức: *
                    </label>
                    <input
                      type="text"
                      required
                      value={formData.name}
                      onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                      placeholder="Ví dụ: Alex Nguyễn"
                      className="w-full px-4 py-3 rounded-xl bg-midnight-900 border border-slate-800 text-white placeholder:text-slate-600 focus:outline-none focus:border-emerald-500 font-mono text-xs sm:text-sm"
                    />
                  </div>

                  {/* Email */}
                  <div className="space-y-1.5">
                    <label className="text-xs font-mono text-slate-300 font-bold">
                      Địa chỉ Email phản hồi: *
                    </label>
                    <input
                      type="email"
                      required
                      value={formData.email}
                      onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                      placeholder="alex@company.com"
                      className="w-full px-4 py-3 rounded-xl bg-midnight-900 border border-slate-800 text-white placeholder:text-slate-600 focus:outline-none focus:border-emerald-500 font-mono text-xs sm:text-sm"
                    />
                  </div>

                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  
                  {/* Project Type */}
                  <div className="space-y-1.5">
                    <label className="text-xs font-mono text-slate-300 font-bold">
                      Mục đích / Loại Dự án:
                    </label>
                    <select
                      value={formData.projectType}
                      onChange={(e) => setFormData({ ...formData, projectType: e.target.value })}
                      className="w-full px-4 py-3 rounded-xl bg-midnight-900 border border-slate-800 text-white focus:outline-none focus:border-emerald-500 font-mono text-xs sm:text-sm"
                    >
                      <option value="Full-Stack Web App">Full-Stack Web Application</option>
                      <option value="Creative UI/UX & Web Audio">Creative UI/UX & Web Audio</option>
                      <option value="High-Throughput Microservice">High-Throughput Microservice</option>
                      <option value="AI Agents & Automation">AI Agents & Workflow Automation</option>
                      <option value="Tech Lead / Architecture Consulting">Tư vấn Kiến trúc & Tech Lead</option>
                      <option value="Other Quest">Ý tưởng độc đáo khác</option>
                    </select>
                  </div>

                  {/* Coffee Offering */}
                  <div className="space-y-1.5">
                    <label className="text-xs font-mono text-slate-300 font-bold flex items-center gap-1">
                      <Coffee className="w-3.5 h-3.5 text-amber-400" />
                      <span>Lễ vật cà phê đính kèm:</span>
                    </label>
                    <select
                      value={formData.coffeeOffering}
                      onChange={(e) => setFormData({ ...formData, coffeeOffering: e.target.value })}
                      className="w-full px-4 py-3 rounded-xl bg-midnight-900 border border-slate-800 text-amber-200 focus:outline-none focus:border-emerald-500 font-mono text-xs sm:text-sm"
                    >
                      <option value="1 Ly Robusta Đen Đậm Đặc ☕">1 Ly Robusta Đen Đậm Đặc ☕</option>
                      <option value="X2 Espresso Shot Không Đường ☕⚡">X2 Espresso Shot Không Đường ☕⚡</option>
                      <option value="1 Ly Bạc Xỉu Sữa Đặc Đêm Khuya 🥛">1 Ly Bạc Xỉu Sữa Đặc Đêm Khuya 🥛</option>
                      <option value="Full Thùng Nước Tăng Lực Monster 🔋">Full Thùng Monster Energy 🔋</option>
                    </select>
                  </div>

                </div>

                {/* Message */}
                <div className="space-y-1.5">
                  <label className="text-xs font-mono text-slate-300 font-bold">
                    Lời triệu hồi / Mô tả dự án: *
                  </label>
                  <textarea
                    required
                    rows={4}
                    value={formData.message}
                    onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                    placeholder="Mô tả mục tiêu, timeline dự kiến hoặc bất kỳ điều gì bạn muốn chia sẻ..."
                    className="w-full px-4 py-3 rounded-xl bg-midnight-900 border border-slate-800 text-white placeholder:text-slate-600 focus:outline-none focus:border-emerald-500 font-mono text-xs sm:text-sm resize-none"
                  />
                </div>

                {/* Submit button */}
                <button
                  type="submit"
                  disabled={loading}
                  className="w-full py-3.5 rounded-2xl bg-gradient-to-r from-emerald-500 via-teal-400 to-cyan-500 text-midnight-950 font-bold font-mono text-sm flex items-center justify-center gap-2 shadow-glow-mint hover:scale-[1.01] active:scale-[0.99] transition-all disabled:opacity-50"
                >
                  {loading ? (
                    <span>Đang niệm phép gửi thư... ⏳</span>
                  ) : (
                    <>
                      <Send className="w-4 h-4" />
                      <span>Cast Summon Spell (Phát Tín Hiệu) ⚡</span>
                    </>
                  )}
                </button>
              </form>
            )}

          </div>

          {/* Direct Channels Cards */}
          <div className="lg:col-span-5 space-y-4">
            
            <div className="p-6 rounded-3xl glass-panel border border-slate-800 space-y-4">
              <h3 className="font-display font-bold text-xl text-white flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-talisman-yellow" />
                <span>Direct Spectral Channels</span>
              </h3>
              <p className="text-xs sm:text-sm text-slate-400 font-mono leading-relaxed">
                Thích trao đổi trực tiếp qua các kênh liên lạc tức thời? Bạn có thể liên hệ Ma Cà Tưng qua các đường dẫn dưới đây:
              </p>

              <div className="space-y-2.5 pt-2">
                <a
                  href="mailto:summon@macatung.dev"
                  onClick={() => sound.playClick()}
                  className="p-3.5 rounded-2xl bg-midnight-900/90 border border-slate-800 hover:border-emerald-500/50 flex items-center justify-between group transition-all"
                >
                  <div className="flex items-center gap-3">
                    <div className="p-2 rounded-xl bg-emerald-500/10 text-emerald-400">
                      <Mail className="w-4 h-4" />
                    </div>
                    <div>
                      <div className="text-xs font-mono font-bold text-white group-hover:text-phantom-mint">Email</div>
                      <div className="text-[11px] font-mono text-slate-400">summon@macatung.dev</div>
                    </div>
                  </div>
                  <span className="text-xs font-mono text-slate-500 group-hover:text-white">→</span>
                </a>

                <a
                  href="https://github.com/macatung"
                  target="_blank"
                  rel="noreferrer"
                  onClick={() => sound.playClick()}
                  className="p-3.5 rounded-2xl bg-midnight-900/90 border border-slate-800 hover:border-emerald-500/50 flex items-center justify-between group transition-all"
                >
                  <div className="flex items-center gap-3">
                    <div className="p-2 rounded-xl bg-slate-800 text-slate-200">
                      <GithubIcon className="w-4 h-4" />
                    </div>
                    <div>
                      <div className="text-xs font-mono font-bold text-white group-hover:text-phantom-mint">GitHub</div>
                      <div className="text-[11px] font-mono text-slate-400">github.com/macatung</div>
                    </div>
                  </div>
                  <span className="text-xs font-mono text-slate-500 group-hover:text-white">→</span>
                </a>

                <a
                  href="https://t.me"
                  target="_blank"
                  rel="noreferrer"
                  onClick={() => sound.playClick()}
                  className="p-3.5 rounded-2xl bg-midnight-900/90 border border-slate-800 hover:border-cyan-500/50 flex items-center justify-between group transition-all"
                >
                  <div className="flex items-center gap-3">
                    <div className="p-2 rounded-xl bg-cyan-500/10 text-cyan-400">
                      <MessageSquare className="w-4 h-4" />
                    </div>
                    <div>
                      <div className="text-xs font-mono font-bold text-white group-hover:text-cyan-300">Telegram</div>
                      <div className="text-[11px] font-mono text-slate-400">@macatung_dev</div>
                    </div>
                  </div>
                  <span className="text-xs font-mono text-slate-500 group-hover:text-white">→</span>
                </a>

                <a
                  href="https://linkedin.com"
                  target="_blank"
                  rel="noreferrer"
                  onClick={() => sound.playClick()}
                  className="p-3.5 rounded-2xl bg-midnight-900/90 border border-slate-800 hover:border-blue-500/50 flex items-center justify-between group transition-all"
                >
                  <div className="flex items-center gap-3">
                    <div className="p-2 rounded-xl bg-blue-500/10 text-blue-400">
                      <LinkedinIcon className="w-4 h-4" />
                    </div>
                    <div>
                      <div className="text-xs font-mono font-bold text-white group-hover:text-blue-300">LinkedIn</div>
                      <div className="text-[11px] font-mono text-slate-400">linkedin.com/in/macatung</div>
                    </div>
                  </div>
                  <span className="text-xs font-mono text-slate-500 group-hover:text-white">→</span>
                </a>
              </div>
            </div>

            {/* Midnight SLA Badge */}
            <div className="p-4 rounded-2xl bg-midnight-900/60 border border-slate-800 flex items-center gap-3 text-xs font-mono text-slate-400">
              <span className="text-xl">🛡️</span>
              <div>
                <strong className="text-white block">Midnight SLA Commitment:</strong>
                Mọi tin nhắn đều được phản hồi trong vòng tối đa 24 giờ.
              </div>
            </div>

          </div>

        </div>

      </div>
    </section>
  );
};

// resources/js/Components/contact/ContactSection.vue
<script setup lang="ts">
import { useForm, usePage } from '@inertiajs/vue3';
import { ref } from 'vue';
import confetti from 'canvas-confetti';
import { sound } from '@/audio/soundEffects';
import Icons from '@/Components/ui/Icons.vue';
import { useI18n } from '@/composables/useI18n';

const projectTypes = [
  'Full-Stack Web App',
  'Creative UI/UX & Web Audio',
  'High-Throughput Microservice',
  'AI Agents & Automation',
  'Tech Lead / Architecture Consulting',
  'Other Quest',
];

const coffeeOfferings = [
  '1 Ly Cà Phê Muối Nửa Đêm',
  'Cold Brew Robusta 100%',
  'Espresso Đậm Đặc Double Shot',
  'Trà Đào Cam Sả',
];

const form = useForm({
  name: '',
  email: '',
  project_type: 'Full-Stack Web App',
  coffee_offering: '1 Ly Cà Phê Muối Nửa Đêm',
  message: '',
});

const page = usePage();
const { t } = useI18n();
const copySuccess = ref(false);
const submittedReferenceId = ref<string>('');
const isSubmitted = ref(false);

const copyEmail = async () => {
  try {
    if (typeof navigator !== 'undefined' && navigator.clipboard) {
      await navigator.clipboard.writeText('dev@macatung.dev');
    }
    copySuccess.value = true;
    sound.playClick();
    setTimeout(() => {
      copySuccess.value = false;
    }, 2500);
  } catch {
    // Fallback
  }
};

const handleSubmit = () => {
  if (form.processing) return;

  sound.playTalisman();

  form.post('/contact', {
    preserveScroll: true,
    onSuccess: (pageProps: any) => {
      const flash = pageProps?.props?.flash || (page.props as any)?.flash;
      const refId = flash?.reference_id || 'SUMMON-0000';
      submittedReferenceId.value = refId;
      isSubmitted.value = true;

      sound.playSuccess();

      try {
        confetti({
          particleCount: 80,
          spread: 70,
          origin: { y: 0.6 },
          colors: ['#00f5a0', '#ffd166', '#ff0054'],
        });
      } catch {
        // Fallback for headless environments
      }

      form.reset();
    },
    onError: () => {
      sound.playClick();
    },
  });
};

const resetForm = () => {
  form.reset();
  form.clearErrors();
  isSubmitted.value = false;
  submittedReferenceId.value = '';
};

const projectTypeLabel = (value: string) => value === 'Other Quest' ? t('contact.projectOther') : value;
const coffeeLabel = (value: string) => value === '1 Ly Cà Phê Muối Nửa Đêm' ? t('contact.coffeeSalt') : value === 'Espresso Đậm Đặc Double Shot' ? t('contact.coffeeEspresso') : value === 'Trà Đào Cam Sả' ? t('contact.coffeeTea') : value;
</script>

<template>
  <section id="contact" class="scroll-mt-24 w-full py-16 sm:py-20 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-left">
    <!-- Header -->
    <div class="flex flex-col items-start mb-10">
      <span class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-phantom-mint text-xs font-mono mb-3 whitespace-nowrap select-none">
        🔮 {{ t('contact.badge') }}
      </span>
      <h2 class="text-3xl sm:text-4xl lg:text-5xl font-display font-extrabold text-white tracking-tight">
        {{ t('contact.heading') }} <span class="text-phantom-mint">{{ t('contact.headingAccent') }}</span>
      </h2>
      <p class="text-sm sm:text-base text-slate-400 mt-2 max-w-2xl font-sans">
        {{ t('contact.descriptionFull') }}
      </p>
    </div>

    <!-- Altar Grid: 2 Columns -->
    <div class="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
      <!-- Left Column: Direct Channels & Ritual Guidelines (5 Columns) -->
      <div class="lg:col-span-5 flex flex-col gap-6">
        <!-- Direct Spectral Channel Card -->
        <div class="glass-panel p-6 sm:p-8 rounded-3xl border border-white/10 text-left">
          <h3 class="font-display font-bold text-lg sm:text-xl text-white mb-2">{{ t('contact.channel') }}</h3>
          <p class="text-xs sm:text-sm text-slate-400 font-sans leading-relaxed mb-6">
            {{ t('contact.channelDesc') }}
          </p>

          <!-- Email Copy Pill -->
          <div class="p-4 rounded-2xl bg-midnight-950/80 border border-white/10 flex items-center justify-between gap-3 mb-6">
            <div class="flex items-center gap-3 min-w-0">
              <div class="w-10 h-10 rounded-xl bg-midnight-900 border border-white/10 flex items-center justify-center text-phantom-mint shrink-0">
                <Icons name="Mail" :size="18" />
              </div>
              <div class="min-w-0">
                <div class="text-[10px] font-mono text-slate-400 uppercase tracking-wider whitespace-nowrap">{{ t('contact.directEmail') }}</div>
                <div class="font-mono text-xs sm:text-sm font-bold text-white truncate">dev@macatung.dev</div>
              </div>
            </div>
            <button
              type="button"
              class="px-3 py-2 rounded-xl bg-white/5 hover:bg-phantom-mint hover:text-midnight-950 text-slate-300 text-xs font-mono font-semibold transition-all shrink-0 min-h-[38px] flex items-center gap-1.5 whitespace-nowrap"
              @click="copyEmail"
            >
              <Icons v-if="copySuccess" name="Check" :size="14" />
              <Icons v-else name="Copy" :size="14" />
              <span>{{ copySuccess ? t('contact.copied') : 'Copy' }}</span>
            </button>
          </div>

          <!-- Status & Availability -->
          <div class="space-y-3 text-xs font-mono">
            <div class="flex items-center justify-between p-3 rounded-xl bg-midnight-950/50 border border-white/5">
              <span class="text-slate-400">{{ t('contact.timezone') }}</span>
              <span class="text-slate-200 font-semibold whitespace-nowrap">GMT+7 (Midnight Realm)</span>
            </div>
            <div class="flex items-center justify-between p-3 rounded-xl bg-midnight-950/50 border border-white/5">
              <span class="text-slate-400">{{ t('contact.questStatus') }}</span>
              <span class="text-phantom-mint font-semibold flex items-center gap-1.5 whitespace-nowrap">
                <span class="w-2 h-2 rounded-full bg-phantom-mint animate-pulse" />
                {{ t('contact.available') }}
              </span>
            </div>
            <div class="flex items-center justify-between p-3 rounded-xl bg-midnight-950/50 border border-white/5">
              <span class="text-slate-400">{{ t('contact.responseTime') }}</span>
              <span class="text-talisman-gold font-semibold whitespace-nowrap">{{ t('contact.responsePromise') }}</span>
            </div>
          </div>
        </div>

        <!-- Social & CV Card -->
        <div class="glass-panel p-6 rounded-3xl border border-white/10 space-y-4">
          <div class="text-xs font-mono text-slate-400 uppercase tracking-wider mb-2">{{ t('contact.network') }}</div>
          
          <div class="flex flex-wrap gap-2.5">
            <a
              href="https://github.com/macatung"
              target="_blank"
              rel="noopener noreferrer"
              class="px-4 py-2.5 rounded-xl bg-midnight-900 border border-white/10 hover:border-phantom-mint text-slate-300 hover:text-white text-xs font-mono transition-all flex items-center gap-2 min-h-[44px] whitespace-nowrap"
            >
              <Icons name="Github" :size="15" />
              <span>GitHub</span>
            </a>
            <a
              href="https://linkedin.com"
              target="_blank"
              rel="noopener noreferrer"
              class="px-4 py-2.5 rounded-xl bg-midnight-900 border border-white/10 hover:border-phantom-mint text-slate-300 hover:text-white text-xs font-mono transition-all flex items-center gap-2 min-h-[44px] whitespace-nowrap"
            >
              <Icons name="ExternalLink" :size="15" />
              <span>LinkedIn</span>
            </a>
            <a
              href="https://t.me/macatung"
              target="_blank"
              rel="noopener noreferrer"
              class="px-4 py-2.5 rounded-xl bg-midnight-900 border border-white/10 hover:border-phantom-cyan text-slate-300 hover:text-white text-xs font-mono transition-all flex items-center gap-2 min-h-[44px] whitespace-nowrap"
            >
              <span>✈️</span>
              <span>Telegram</span>
            </a>
          </div>

          <!-- Studio Inquiries Badge -->
          <div class="pt-3 border-t border-white/5 flex items-center justify-between">
            <div class="flex items-center gap-2">
              <span class="text-lg">🚀</span>
              <div class="text-xs font-mono">
                <div class="text-white font-bold">Studio Collaboration</div>
                <div class="text-[10px] text-slate-400">Architecture, AI &amp; Product Inquiries</div>
              </div>
            </div>
            <a
              href="https://github.com/macatung"
              target="_blank"
              rel="noopener noreferrer"
              class="px-3 py-1.5 rounded-xl bg-phantom-mint/10 border border-phantom-mint/30 text-phantom-mint hover:bg-phantom-mint hover:text-midnight-950 text-xs font-mono font-bold transition-all flex items-center gap-1.5 whitespace-nowrap"
            >
              <span>GitHub</span>
              <span>↗</span>
            </a>
          </div>
        </div>
      </div>

      <!-- Right Column: Summoning Form (7 Columns) -->
      <div class="lg:col-span-7">
        <div class="glass-panel p-6 sm:p-8 rounded-3xl border border-white/10 text-left relative">
          <!-- Success Overlay -->
          <div
            v-if="isSubmitted || form.wasSuccessful"
            class="p-8 text-center flex flex-col items-center justify-center space-y-4 min-h-[400px]"
          >
            <div class="w-16 h-16 rounded-full bg-phantom-mint/10 border-2 border-phantom-mint flex items-center justify-center text-3xl shadow-glow-mint">
              ✨
            </div>
            <h3 class="text-2xl font-display font-bold text-white">{{ t('contact.success') }}</h3>
            <p class="text-sm text-slate-300 max-w-md leading-relaxed font-sans">
              {{ t('contact.successDesc') }} <span class="font-mono text-phantom-mint font-bold">{{ submittedReferenceId || ($page.props.flash as any)?.reference_id || 'SUMMON-XXXX' }}</span>. {{ t('contact.successTail') }}
            </p>
            <button
              type="button"
              class="mt-4 px-6 py-3 rounded-xl bg-midnight-800 border border-white/10 hover:border-phantom-mint text-white font-mono text-xs font-bold transition-all min-h-[44px]"
              @click="resetForm"
            >
              {{ t('contact.sendAnother') }}
            </button>
          </div>

          <!-- The Form -->
          <form v-else class="space-y-5" @submit.prevent="handleSubmit">
            <!-- Name & Email Inputs -->
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label class="block text-xs font-mono text-slate-300 uppercase tracking-wider mb-1.5 whitespace-nowrap">
                  {{ t('contact.nameLabel') }} <span class="text-rose-400">*</span>
                </label>
                <input
                  v-model="form.name"
                  type="text"
                  placeholder="e.g. Founder Minh / Partner Anh"
                  class="w-full px-4 py-3 rounded-xl bg-midnight-900 border border-white/10 text-white font-sans text-sm placeholder-slate-600 focus:border-phantom-mint focus:outline-none min-h-[44px] transition-colors"
                  :class="{ 'border-rose-500/80': form.errors.name }"
                  @input="form.clearErrors('name')"
                />
                <span v-if="form.errors.name" class="text-[11px] font-mono text-rose-400 mt-1 block">{{ form.errors.name }}</span>
              </div>

              <div>
                <label class="block text-xs font-mono text-slate-300 uppercase tracking-wider mb-1.5 whitespace-nowrap">
                  {{ t('contact.emailLabel') }} <span class="text-rose-400">*</span>
                </label>
                <input
                  v-model="form.email"
                  type="email"
                  placeholder="e.g. partner@company.com"
                  class="w-full px-4 py-3 rounded-xl bg-midnight-900 border border-white/10 text-white font-sans text-sm placeholder-slate-600 focus:border-phantom-mint focus:outline-none min-h-[44px] transition-colors"
                  :class="{ 'border-rose-500/80': form.errors.email }"
                  @input="form.clearErrors('email')"
                />
                <span v-if="form.errors.email" class="text-[11px] font-mono text-rose-400 mt-1 block">{{ form.errors.email }}</span>
              </div>
            </div>

            <!-- Project Type Selector -->
            <div>
              <label class="block text-xs font-mono text-slate-300 uppercase tracking-wider mb-2 whitespace-nowrap">
                {{ t('contact.typeLabel') }}
              </label>
              <div class="grid grid-cols-1 sm:grid-cols-2 gap-2">
                <button
                  v-for="type in projectTypes"
                  :key="type"
                  type="button"
                  class="p-2.5 rounded-xl border text-left text-xs font-sans font-medium transition-all min-h-[44px] flex items-center justify-between whitespace-nowrap"
                  :class="form.project_type === type
                    ? 'bg-midnight-800 border-phantom-mint text-phantom-mint shadow-glow-mint font-bold'
                    : 'bg-midnight-950/60 border-white/5 hover:border-white/20 text-slate-400 hover:text-slate-200'"
                  @click="form.project_type = type; form.clearErrors('project_type'); sound.playClick()"
                >
                  <span class="truncate">{{ projectTypeLabel(type) }}</span>
                  <span v-if="form.project_type === type" class="text-phantom-mint font-bold">✓</span>
                </button>
              </div>
              <span v-if="form.errors.project_type" class="text-[11px] font-mono text-rose-400 mt-1 block">{{ form.errors.project_type }}</span>
            </div>

            <!-- Coffee Offering -->
            <div>
              <label class="block text-xs font-mono text-slate-300 uppercase tracking-wider mb-2 whitespace-nowrap">
                {{ t('contact.coffeeLabel') }}
              </label>
              <div class="grid grid-cols-1 sm:grid-cols-2 gap-2">
                <button
                  v-for="coffee in coffeeOfferings"
                  :key="coffee"
                  type="button"
                  class="p-2.5 rounded-xl border text-left text-xs font-sans transition-all min-h-[44px] flex items-center justify-between whitespace-nowrap"
                  :class="form.coffee_offering === coffee
                    ? 'bg-midnight-800 border-talisman-gold text-talisman-gold shadow-glow-talisman font-bold'
                    : 'bg-midnight-950/60 border-white/5 hover:border-white/20 text-slate-400 hover:text-slate-200'"
                  @click="form.coffee_offering = coffee; form.clearErrors('coffee_offering'); sound.playClick()"
                >
                  <span class="truncate">☕ {{ coffeeLabel(coffee) }}</span>
                  <span v-if="form.coffee_offering === coffee" class="text-talisman-gold font-bold">✓</span>
                </button>
              </div>
              <span v-if="form.errors.coffee_offering" class="text-[11px] font-mono text-rose-400 mt-1 block">{{ form.errors.coffee_offering }}</span>
            </div>

            <!-- Message Detail Input -->
            <div>
              <label class="block text-xs font-mono text-slate-300 uppercase tracking-wider mb-1.5 whitespace-nowrap">
                {{ t('contact.messageLabel') }} <span class="text-rose-400">*</span>
              </label>
              <textarea
                v-model="form.message"
                rows="4"
                :placeholder="t('contact.messagePlaceholder')"
                class="w-full p-4 rounded-xl bg-midnight-900 border border-white/10 text-white font-sans text-sm placeholder-slate-600 focus:border-phantom-mint focus:outline-none transition-colors"
                :class="{ 'border-rose-500/80': form.errors.message }"
                @input="form.clearErrors('message')"
              />
              <span v-if="form.errors.message" class="text-[11px] font-mono text-rose-400 mt-1 block">{{ form.errors.message }}</span>
            </div>

            <!-- Submit Button -->
            <button
              type="submit"
              class="w-full py-4 rounded-2xl font-display font-extrabold text-sm sm:text-base transition-all shadow-xl flex items-center justify-center gap-2 min-h-[52px] whitespace-nowrap"
              :class="form.processing
                ? 'bg-slate-700 text-slate-400 cursor-not-allowed animate-pulse'
                : 'bg-gradient-to-r from-phantom-mint via-phantom-cyan to-talisman-gold text-midnight-950 hover:brightness-110 active:scale-[0.99] shadow-glow-mint'"
              :disabled="form.processing"
            >
              <span v-if="form.processing">⏳ {{ t('contact.submitting') }}</span>
              <span v-else>🚀 {{ t('contact.submit') }}</span>
            </button>
          </form>
        </div>
      </div>
    </div>
  </section>
</template>
