// src/components/layout/Footer.tsx
import React from 'react';
import { sound } from '../../audio/soundEffects';
import confetti from 'canvas-confetti';
import { ArrowUp, Heart, Coffee, MessageSquare } from 'lucide-react';
import { GithubIcon, LinkedinIcon } from '../ui/Icons';

export const Footer: React.FC = () => {
  const scrollToTop = () => {
    sound.playHop(1.8);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleEasterEgg = () => {
    sound.playSuccess();
    confetti({
      particleCount: 50,
      spread: 60,
      origin: { y: 0.9 },
      colors: ['#ffd166', '#00f5a0', '#ff0054'],
    });
  };

  return (
    <footer className="relative border-t border-slate-800/80 bg-midnight-950/90 pt-16 pb-12 overflow-hidden">
      
      {/* Subtle top glow */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-3/4 h-px bg-gradient-to-r from-transparent via-emerald-500/40 to-transparent" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        <div className="flex flex-col md:flex-row items-center justify-between gap-8 pb-12 border-b border-slate-800/80">
          
          {/* Brand Info */}
          <div className="text-center md:text-left space-y-2">
            <div className="flex items-center justify-center md:justify-start gap-2">
              <span className="font-display font-bold text-xl text-white">
                macatung<span className="text-phantom-mint">.dev</span>
              </span>
              <span className="px-2 py-0.5 rounded text-[10px] font-mono uppercase bg-emerald-500/10 text-emerald-300 border border-emerald-500/30">
                Code at midnight
              </span>
            </div>
            <p className="text-xs font-mono text-slate-400 max-w-sm">
              Trang thông tin & portfolio của Ma Cà Tưng — Nơi các ý tưởng kỳ ảo được hiện thực hóa bằng công nghệ hiện đại.
            </p>
          </div>

          {/* Center Links */}
          <div className="flex flex-wrap items-center justify-center gap-6 text-xs font-mono text-slate-400">
            <a
              href="#about"
              onClick={() => sound.playClick()}
              className="hover:text-phantom-mint transition-colors"
            >
              // Origin
            </a>
            <a
              href="#projects"
              onClick={() => sound.playClick()}
              className="hover:text-phantom-mint transition-colors"
            >
              // Grimoire
            </a>
            <a
              href="#skills"
              onClick={() => sound.playClick()}
              className="hover:text-phantom-mint transition-colors"
            >
              // Talismans
            </a>
            <a
              href="#terminal"
              onClick={() => sound.playClick()}
              className="hover:text-phantom-mint transition-colors"
            >
              // Terminal
            </a>
            <a
              href="#talisman-gen"
              onClick={() => sound.playClick()}
              className="hover:text-talisman-yellow transition-colors"
            >
              // Thỉnh Bùa
            </a>
          </div>

          {/* Hop To Top Button */}
          <div>
            <button
              onClick={scrollToTop}
              className="px-4 py-2.5 rounded-2xl glass-panel-glow border border-emerald-500/40 text-emerald-300 hover:text-white font-mono text-xs flex items-center gap-2 shadow-glow-mint hover:scale-105 active:scale-95 transition-all"
            >
              <ArrowUp className="w-4 h-4 animate-bounce" />
              <span>Hop to Top 🦘</span>
            </button>
          </div>

        </div>

        {/* Bottom Bar */}
        <div className="pt-8 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs font-mono text-slate-500">
          
          {/* Copyright with Easter Egg */}
          <div className="flex items-center gap-1.5 flex-wrap justify-center">
            <span>© 2026 macatung.dev • Crafted with</span>
            <button
              onClick={handleEasterEgg}
              className="text-rose-500 hover:scale-125 transition-transform"
              title="Click me for a midnight blessing!"
            >
              <Heart className="w-3.5 h-3.5 fill-rose-500" />
            </button>
            <span>&</span>
            <span className="text-amber-400 flex items-center gap-1">
              <Coffee className="w-3.5 h-3.5 inline" /> Dark Robusta
            </span>
          </div>

          {/* Socials */}
          <div className="flex items-center gap-4 text-slate-400">
            <a
              href="https://github.com/macatung"
              target="_blank"
              rel="noreferrer"
              onClick={() => sound.playClick()}
              className="hover:text-white transition-colors"
            >
              <GithubIcon className="w-4 h-4" />
            </a>
            <a
              href="https://linkedin.com"
              target="_blank"
              rel="noreferrer"
              onClick={() => sound.playClick()}
              className="hover:text-cyan-400 transition-colors"
            >
              <LinkedinIcon className="w-4 h-4" />
            </a>
            <a
              href="https://t.me"
              target="_blank"
              rel="noreferrer"
              onClick={() => sound.playClick()}
              className="hover:text-blue-400 transition-colors"
            >
              <MessageSquare className="w-4 h-4" />
            </a>
          </div>

        </div>

      </div>
    </footer>
  );
};

// resources/js/Components/layout/Footer.vue
<script setup lang="ts">
import { ref } from 'vue';
import confetti from 'canvas-confetti';
import { sound } from '@/audio/soundEffects';
import Icons from '@/Components/ui/Icons.vue';
import MiniMascotLogo from '@/Components/mascot/MiniMascotLogo.vue';

const heartClicks = ref(0);

const scrollToTop = () => {
  sound.playHop(1.2);
  if (typeof window !== 'undefined') {
    window.scrollTo({
      top: 0,
      behavior: 'smooth',
    });
  }
};

const triggerHeartEasterEgg = (e: MouseEvent) => {
  heartClicks.value++;
  sound.playSuccess();

  try {
    if (typeof window !== 'undefined') {
      const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
      const x = (rect.left + rect.width / 2) / window.innerWidth;
      const y = (rect.top + rect.height / 2) / window.innerHeight;

      confetti({
        particleCount: 45,
        spread: 60,
        origin: { x, y },
        colors: ['#00f5a0', '#ffd166', '#ff0054', '#9d4edd'],
        disableForReducedMotion: true,
      });
    }
  } catch {
    // Fallback
  }
};
</script>

<template>
  <footer class="footer relative z-10 border-t border-white/5 py-12 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-left select-none">
    <!-- Top Bar with Hop-to-Top Trigger -->
    <div class="flex flex-col sm:flex-row items-center justify-between pb-8 border-b border-white/5 gap-4">
      <div class="flex items-center gap-3">
        <MiniMascotLogo size="sm" :animated="true" />
        <span class="font-display font-bold text-base sm:text-lg text-white">
          macatung<span class="text-phantom-mint">.dev</span>
        </span>
        <span class="text-xs font-mono text-slate-500 hidden sm:inline">— Code at midnight.</span>
      </div>

      <!-- Hop-to-Top Button -->
      <button
        type="button"
        class="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-midnight-900 border border-white/10 text-slate-300 hover:text-phantom-mint hover:border-phantom-mint/40 transition-all text-xs font-mono group min-h-[44px]"
        @click="scrollToTop"
      >
        <span>Về Đầu Trang</span>
        <Icons name="ChevronUp" :size="16" class="group-hover:-translate-y-1 transition-transform" />
      </button>
    </div>

    <!-- Navigation Columns Grid -->
    <div class="grid grid-cols-2 md:grid-cols-4 gap-8 py-10 border-b border-white/5 text-xs font-sans">
      <!-- Col 1: Grimoire & Lore -->
      <div>
        <h4 class="font-mono text-slate-400 uppercase tracking-wider mb-3 text-[11px]">Grimoire & Lore</h4>
        <ul class="space-y-2 text-slate-400">
          <li><a href="#hero" class="hover:text-phantom-mint transition-colors">Vương Quốc Đêm</a></li>
          <li><a href="#about" class="hover:text-phantom-mint transition-colors">Triết Lý 00:00 AM</a></li>
          <li><a href="#projects" class="hover:text-phantom-mint transition-colors">Hệ Thống Grimoire</a></li>
        </ul>
      </div>

      <!-- Col 2: Interactive Labs -->
      <div>
        <h4 class="font-mono text-slate-400 uppercase tracking-wider mb-3 text-[11px]">Thí Nghiệm & Pháp Bảo</h4>
        <ul class="space-y-2 text-slate-400">
          <li><a href="/projects" class="hover:text-phantom-mint transition-colors">Kho Dự Án Grimoire</a></li>
          <li><a href="/game" class="hover:text-phantom-mint transition-colors">Phòng Máy Rune Typer</a></li>
          <li><a href="/talisman" class="hover:text-phantom-mint transition-colors">Lò Luyện Bùa Chú</a></li>
        </ul>
      </div>

      <!-- Col 3: Terminal & Altar -->
      <div>
        <h4 class="font-mono text-slate-400 uppercase tracking-wider mb-3 text-[11px]">Công Cụ & Tương Tác</h4>
        <ul class="space-y-2 text-slate-400">
          <li><a href="#terminal" class="hover:text-phantom-mint transition-colors">Midnight Terminal CLI</a></li>
          <li><a href="#contact" class="hover:text-phantom-mint transition-colors">Bàn Thờ Triệu Hồi</a></li>
          <li><a href="https://github.com/macatung" target="_blank" rel="noopener noreferrer" class="hover:text-phantom-mint transition-colors">GitHub Repository</a></li>
        </ul>
      </div>

      <!-- Col 4: Status -->
      <div>
        <h4 class="font-mono text-slate-400 uppercase tracking-wider mb-3 text-[11px]">Trạng Thái Hệ Thống</h4>
        <div class="space-y-1.5 text-slate-400 font-mono text-[11px]">
          <div class="flex items-center gap-1.5 text-phantom-mint">
            <span class="w-1.5 h-1.5 rounded-full bg-phantom-mint animate-pulse" />
            <span>100% Uptime Pledge</span>
          </div>
          <div>Audio: Web Audio API (0 asset)</div>
          <div>Framework: Vue 3 + Laravel 11</div>
          <div class="pt-1">
            <a href="/admin" class="text-slate-400 hover:text-phantom-mint transition-colors flex items-center gap-1">
              <span>⚙️ Quản Trị CMS</span>
              <span>→</span>
            </a>
          </div>
        </div>
      </div>
    </div>

    <!-- Bottom Attribution & Heart Easter Egg Bar -->
    <div class="pt-8 flex flex-col sm:flex-row items-center justify-between text-xs text-slate-500 font-mono gap-4">
      <p class="text-center sm:text-left">
        © 2026 macatung.dev — Crafted with Laravel 11, Inertia.js, Vue 3 & Midnight Magic.
      </p>

      <!-- Easter Egg Heart Button -->
      <div class="flex items-center gap-1.5 text-slate-400 select-none">
        <span>Crafted with</span>
        <button
          type="button"
          class="text-rose-400 hover:scale-125 active:scale-95 transition-transform cursor-pointer p-1 min-h-[32px] min-w-[32px] flex items-center justify-center focus:outline-none"
          title="Bấm để kích hoạt Midnight Love Easter Egg"
          @click="triggerHeartEasterEgg"
        >
          ❤️
        </button>
        <span>& Midnight Robusta</span>
        <span v-if="heartClicks > 0" class="text-phantom-mint font-bold ml-1">({{ heartClicks }})</span>
      </div>
    </div>
  </footer>
</template>
