// resources/js/Components/terminal/MidnightTerminal.vue
<script setup lang="ts">
import { ref, nextTick } from 'vue';
import { projectsData } from '@/data/projectsData';
import { skillsData } from '@/data/skillsData';
import { sound } from '@/audio/soundEffects';
import { trackEvent } from '@/utils/analytics';

export interface TerminalLog {
  id: string;
  type: 'input' | 'output' | 'system' | 'error';
  text: string;
  timestamp: string;
}

const emit = defineEmits<{
  (e: 'hop-requested'): void;
  (e: 'summon-requested'): void;
  (e: 'command-executed', cmd: string, output: string): void;
}>();

const prompt = ref('macatung:~$');
const currentInput = ref('');
const history = ref<string[]>([]);
const historyIndex = ref(-1);
const isExpanded = ref(false);
const isCopied = ref(false);
const logs = ref<TerminalLog[]>([
  {
    id: 'init-1',
    type: 'system',
    text: '🌙 Midnight Terminal v1.1.0 — Type "help" or click quick spell buttons below.',
    timestamp: '00:00:00'
  }
]);

const quickSpells = [
  'help',
  'whoami',
  'cv',
  'projects',
  'skills',
  'hop',
  'coffee',
  'talisman',
  'socials',
  'summon',
  'sudo rm -rf bugs',
  'clear'
];

const scrollContainer = ref<HTMLElement | null>(null);
const inputField = ref<HTMLInputElement | null>(null);

const scrollToBottom = () => {
  if (scrollContainer.value) {
    scrollContainer.value.scrollTop = scrollContainer.value.scrollHeight;
  }
};

const toggleExpand = () => {
  isExpanded.value = !isExpanded.value;
  sound.playClick();
};

const execute = (rawCmd: string): string => {
  const trimmed = rawCmd.trim();
  const now = '00:00:00';

  if (!trimmed) {
    logs.value.push({
      id: `log-${Date.now()}`,
      type: 'input',
      text: `${prompt.value} `,
      timestamp: now
    });
    nextTick(scrollToBottom);
    return '';
  }

  history.value.push(trimmed);
  historyIndex.value = -1;

  logs.value.push({
    id: `log-${Date.now()}-in`,
    type: 'input',
    text: `${prompt.value} ${trimmed}`,
    timestamp: now
  });

  const parts = trimmed.split(/\s+/);
  const command = parts[0].toLowerCase();
  const args = parts.slice(1);

  // Track analytics event
  trackEvent('cli_executed', { command });

  let output = '';
  let outType: 'output' | 'error' | 'system' = 'output';

  switch (command) {
    case 'help':
      output = `Available spells:\n• whoami / bio   : Giới thiệu bản thân & định vị\n• cv / resume    : Xem tóm tắt hồ sơ năng lực & CV\n• projects / ls  : Danh sách Grimoire dự án thực chiến\n• skills         : Toàn bộ kho vũ khí kỹ thuật (18 runes)\n• socials        : Các kênh liên lạc (Email, Telegram, GitHub)\n• summon / hire  : Mở bàn thờ triệu hồi / gửi yêu cầu dự án\n• hop            : Cho Ma Cà Tưng nhảy 1 cú cực cao\n• coffee         : Nạp 1 ly Robusta 100% không đường\n• talisman       : Nhận đạo bùa code 0 bug đã khai quang\n• sudo rm -rf bugs : Trừ tà diệt sạch bug trên production\n• clear          : Xóa sạch màn hình terminal`;
      sound.playClick();
      break;
    case 'whoami':
    case 'bio':
      output = '🧙‍♂️ Ma Cà Tưng — Lead Systems Architect & Creative Full-Stack Engineer.\nĐịnh vị: "Code at midnight" — Biến cà phê Robusta nguyên chất thành kiến trúc phân tán siêu tải và giao diện web ma mị.';
      sound.playClick();
      break;
    case 'cv':
    case 'resume':
      output = `══════════════════════════════════════════════════════════
 📄 HỒ SƠ NĂNG LỰC — MACATUNG.DEV (LEAD SYSTEMS ARCHITECT)
══════════════════════════════════════════════════════════
 • Vị Trí    : Lead Full-Stack Architect / Senior Engineer
 • Kinh Nghiệm: > 8 Năm Chinh Chiến Hệ Thống Tải Cao
 • Thế Mạnh  : Laravel, Vue 3, TypeScript, Microservices, Web Audio, High-Concurrency
 • Thành Tựu : +300% Throughput, 99.99% Uptime SLA, Zero Production Crash
 • Trạng Thái: 🟢 Sẵn Sàng Nhận Quest / Hợp Tác Dự Án Mới
 🔗 Kéo xuống mục "Bàn Thờ Triệu Hồi" để tải bản CV chi tiết!`;
      sound.playSuccess();
      break;
    case 'projects':
    case 'ls':
      output = `Grimoire Projects (${projectsData.length} Spells):\n` + projectsData.map((p) => `  [${p.category.toUpperCase()}] ${p.title} — ${p.tagline} (Metrics: ${p.metrics.map(m => m.value).join(' | ')})`).join('\n');
      sound.playClick();
      break;
    case 'skills': {
      const total = skillsData.reduce((acc, cat) => acc + cat.skills.length, 0);
      output = `Skills Arsenal (${total} runes):\n` + skillsData.map((c) => `  ⚡ ${c.title}: ${c.skills.map((s) => `${s.name} (${s.level}%)`).join(', ')}`).join('\n');
      sound.playClick();
      break;
    }
    case 'socials':
    case 'contact':
      output = `📡 Spectral Communication Channels:\n  • Email   : dev@macatung.dev\n  • GitHub  : https://github.com/macatung\n  • Telegram: @macatung_dev\n  • Realm   : GMT+7 (Midnight Zone)`;
      sound.playClick();
      break;
    case 'admin':
      output = '⚙️ [CMS PORTAL] Opening Admin Dashboard at /admin ... Nhấp để quản lý Projects & Contacts: https://macatung.dev/admin';
      sound.playSuccess();
      if (typeof window !== 'undefined') {
        window.location.href = '/admin';
      }
      break;
    case 'hop':
      output = '🧛‍♂️ *HOP!* Ma Cà Tưng hops gracefully over production bugs! (+1 Hop)';
      sound.playHop(1.5);
      emit('hop-requested');
      break;
    case 'coffee':
      output = '☕ Poured 1 cup of Vietnamese Robusta! Caffeine level = 100%. Ready for 4 AM deploy.';
      sound.playSuccess();
      break;
    case 'talisman':
      output = '📜 [BÙA CODE 0 BUG] try { deploy(); } catch { /* PEACE */ } — Khai Quang thành công!';
      sound.playTalisman();
      break;
    case 'slogan':
      output = '✨ "Code at midnight. Deploy with confidence. Rest when the city wakes."';
      sound.playClick();
      break;
    case 'summon':
    case 'hire':
      output = '🔮 Invoking Summoning Altar... Scroll down to offer coffee and initiate project contract!';
      sound.playClick();
      emit('summon-requested');
      break;
    case 'sudo': {
      const sudoArg = args.join(' ');
      if (sudoArg === 'rm -rf bugs' || sudoArg === 'rm -rf /bugs') {
        output = '🔥 [EXORCISM IN PROGRESS] Purging 4,192 bugs from production... 0 bugs remaining. Realm is peaceful and verified 100%!';
        sound.playSuccess();
      } else {
        output = `sudo: ${sudoArg}: command not permitted by midnight council`;
        outType = 'error';
        sound.playClick();
      }
      break;
    }
    case 'clear':
      logs.value = [];
      currentInput.value = '';
      return '';
    default:
      output = `macatung-cli: command not found: "${command}". Type "help" to see available spells.`;
      outType = 'error';
      sound.playClick();
      break;
  }

  logs.value.push({
    id: `log-${Date.now()}-out`,
    type: outType,
    text: output,
    timestamp: now
  });

  emit('command-executed', trimmed, output);
  currentInput.value = '';
  nextTick(scrollToBottom);
  return output;
};

const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === 'ArrowUp') {
    e.preventDefault();
    if (history.value.length === 0) return;
    if (historyIndex.value === -1) {
      historyIndex.value = history.value.length - 1;
    } else if (historyIndex.value > 0) {
      historyIndex.value--;
    }
    if (historyIndex.value >= 0 && historyIndex.value < history.value.length) {
      currentInput.value = history.value[historyIndex.value];
    }
  } else if (e.key === 'ArrowDown') {
    e.preventDefault();
    if (historyIndex.value < history.value.length - 1 && historyIndex.value !== -1) {
      historyIndex.value++;
      currentInput.value = history.value[historyIndex.value];
    } else {
      historyIndex.value = -1;
      currentInput.value = '';
    }
  } else if (e.key === 'Enter') {
    execute(currentInput.value);
  } else if (e.key.length === 1 && !e.ctrlKey && !e.metaKey && !e.altKey) {
    sound.playTerminalKey();
  }
};

const copyLogs = async () => {
  const plainText = logs.value.map((l) => `${l.type === 'input' ? '' : '  '}${l.text}`).join('\n');
  try {
    if (typeof navigator !== 'undefined' && navigator.clipboard) {
      await navigator.clipboard.writeText(plainText);
    }
    isCopied.value = true;
    sound.playClick();
    setTimeout(() => {
      isCopied.value = false;
    }, 2000);
  } catch {
    // Fallback
  }
};

const runSpell = (cmd: string) => {
  execute(cmd);
};

const focusInput = () => {
  if (inputField.value) {
    inputField.value.focus();
  }
};
</script>

<template>
  <div
    class="w-full rounded-2xl border border-white/10 glass-panel overflow-hidden flex flex-col font-mono text-left shadow-2xl transition-all duration-300"
    :class="isExpanded ? 'h-[540px]' : 'h-[420px]'"
    @click="focusInput"
  >
    <!-- Terminal Header / Title Bar -->
    <div class="h-10 bg-midnight-900/90 border-b border-white/10 px-4 flex items-center justify-between select-none shrink-0">
      <!-- Window Controls & Status -->
      <div class="flex items-center gap-2">
        <span class="w-3 h-3 rounded-full bg-rose-500/80 inline-block" />
        <span class="w-3 h-3 rounded-full bg-amber-500/80 inline-block" />
        <span class="w-3 h-3 rounded-full bg-phantom-mint/80 inline-block" />
        <span class="text-xs text-slate-400 font-bold ml-2 hidden sm:inline truncate">
          macatung@midnight-node: ~ (zsh)
        </span>
      </div>

      <!-- Action Buttons -->
      <div class="flex items-center gap-2">
        <button
          type="button"
          class="p-1 rounded text-slate-400 hover:text-white text-xs transition-colors min-h-[32px] px-2 flex items-center gap-1"
          :title="isCopied ? 'Đã sao chép' : 'Sao chép nhật ký'"
          @click.stop="copyLogs"
        >
          <span>{{ isCopied ? '✓ Đã Copy' : '📋 Copy' }}</span>
        </button>
        <button
          type="button"
          class="p-1 rounded text-slate-400 hover:text-white text-xs transition-colors min-h-[32px] px-2"
          :title="isExpanded ? 'Thu nhỏ' : 'Mở rộng'"
          @click.stop="toggleExpand"
        >
          <span>{{ isExpanded ? '🗗' : '🗖' }}</span>
        </button>
      </div>
    </div>

    <!-- Quick Spells Pill Bar -->
    <div class="bg-midnight-950/80 border-b border-white/5 px-3 py-2 flex items-center gap-1.5 overflow-x-auto no-scrollbar select-none shrink-0">
      <span class="text-[10px] text-slate-500 uppercase tracking-wider shrink-0 mr-1 whitespace-nowrap">Spells:</span>
      <button
        v-for="spell in quickSpells"
        :key="spell"
        type="button"
        class="px-2.5 py-1 rounded-md text-[11px] font-mono bg-white/5 hover:bg-phantom-mint hover:text-midnight-950 text-slate-300 transition-all shrink-0 border border-white/5 whitespace-nowrap"
        @click.stop="runSpell(spell)"
      >
        {{ spell }}
      </button>
    </div>

    <!-- Log Output Container -->
    <div
      ref="scrollContainer"
      class="flex-1 p-4 overflow-y-auto space-y-2 text-xs sm:text-sm font-mono leading-relaxed"
    >
      <div
        v-for="log in logs"
        :key="log.id"
        class="break-words whitespace-pre-wrap"
        :class="{
          'text-phantom-mint font-semibold': log.type === 'input',
          'text-slate-300': log.type === 'output',
          'text-amber-300 font-semibold': log.type === 'system',
          'text-rose-400': log.type === 'error'
        }"
      >
        {{ log.text }}
      </div>

      <!-- Live Input Line -->
      <div class="flex items-center gap-2 pt-1 text-xs sm:text-sm">
        <span class="text-phantom-mint font-bold shrink-0">{{ prompt }}</span>
        <input
          ref="inputField"
          v-model="currentInput"
          type="text"
          class="flex-1 bg-transparent border-none outline-none text-slate-100 font-mono text-xs sm:text-sm p-0 focus:ring-0"
          placeholder="Nhập spell (vd: help, cv, projects)..."
          autofocus
          @keydown="handleKeyDown"
        />
      </div>
    </div>
  </div>
</template>

// src/components/terminal/MidnightTerminal.tsx
import React, { useState, useRef, useEffect } from 'react';
import { sound } from '../../audio/soundEffects';
import confetti from 'canvas-confetti';
import { Terminal as TermIcon, CornerDownLeft, Maximize2, Minimize2, Copy, Check } from 'lucide-react';

interface TerminalLine {
  type: 'input' | 'output' | 'error' | 'success' | 'ascii';
  text: string;
}

export const MidnightTerminal: React.FC = () => {
  const [input, setInput] = useState<string>('');
  const [history, setHistory] = useState<string[]>([]);
  const [historyIndex, setHistoryIndex] = useState<number>(-1);
  const [copied, setCopied] = useState<boolean>(false);
  const [isExpanded, setIsExpanded] = useState<boolean>(false);

  const [lines, setLines] = useState<TerminalLine[]>([
    { type: 'output', text: '╔══════════════════════════════════════════════════════════════╗' },
    { type: 'output', text: '║   🔮 MACATUNG-CLI v2.4.0 [NOCTURNE PROTOCOL: ACTIVE]         ║' },
    { type: 'output', text: '║   Slogan: "Code at midnight" | Domain: macatung.dev          ║' },
    { type: 'output', text: '╚══════════════════════════════════════════════════════════════╝' },
    { type: 'output', text: 'Type "help" to summon available commands.' },
  ]);

  const terminalEndRef = useRef<HTMLDivElement | null>(null);
  const inputRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    terminalEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [lines]);

  const handleCommand = (cmd: string) => {
    const trimmed = cmd.trim();
    if (!trimmed) return;

    sound.playTerminalKey();
    setHistory((prev) => [...prev, trimmed]);
    setHistoryIndex(-1);

    const newLines: TerminalLine[] = [...lines, { type: 'input', text: `$ ${trimmed}` }];
    const lower = trimmed.toLowerCase();

    switch (lower) {
      case 'help':
        newLines.push(
          { type: 'output', text: '⚡ AVAILABLE MIDNIGHT COMMANDS:' },
          { type: 'output', text: '  • whoami / bio      : Learn about Ma Cà Tưng' },
          { type: 'output', text: '  • projects / ls     : Explore the grimoire artifacts' },
          { type: 'output', text: '  • skills            : Inspect tech runes & stack' },
          { type: 'output', text: '  • hop               : Trigger a mascot jump' },
          { type: 'output', text: '  • coffee            : Brew a virtual cup of Vietnamese Robusta' },
          { type: 'output', text: '  • talisman          : Summon an ASCII developer talisman' },
          { type: 'output', text: '  • slogan            : Echo the midnight motto' },
          { type: 'output', text: '  • summon / contact  : Transmit a signal to Ma Cà Tưng' },
          { type: 'output', text: '  • sudo rm -rf bugs  : Exorcise all bugs from production' },
          { type: 'output', text: '  • clear             : Cleanse the terminal display' }
        );
        break;

      case 'whoami':
      case 'bio':
        newLines.push(
          { type: 'success', text: '👤 NAME: Ma Cà Tưng (The Hopping Vampire Developer)' },
          { type: 'output', text: '🌙 ALIAS: Night-Crawler & Lead Full-Stack Sorcerer' },
          { type: 'output', text: '📍 DOMAIN: macatung.dev' },
          { type: 'output', text: '⚡ FOCUS: High-performance web apps, zero-latency architectures & pixel-perfect UI/UX.' },
          { type: 'output', text: '☕ FUEL: Dark Roast Vietnamese Robusta (Strength: 999%)' }
        );
        break;

      case 'projects':
      case 'ls':
      case 'ls projects':
        newLines.push(
          { type: 'output', text: '📜 ARTIFACTS IN GRIMOIRE:' },
          { type: 'output', text: '  [1] Nocturne OS         - Cloud micro-workspace (React, Rust WASM)' },
          { type: 'output', text: '  [2] Phantom Flow        - DeFi liquidity engine (Go, Solidity, GraphQL)' },
          { type: 'output', text: '  [3] Grimoire UI         - Physics talisman design system (React 18)' },
          { type: 'output', text: '  [4] Spectral AI Agents  - Autonomous test synthesizer (Python, AST)' },
          { type: 'output', text: '  [5] Kitsune KV          - Ephemeral zero-copy store (Rust Tokio)' },
          { type: 'output', text: '  [6] macatung.dev v2.0   - The official midnight portfolio' },
          { type: 'output', text: 'Tip: Scroll to #projects section to inspect interactive modals.' }
        );
        break;

      case 'skills':
        newLines.push(
          { type: 'output', text: '🔮 TECH STACK MATRIX:' },
          { type: 'output', text: '  [Frontend] : React 18, Next.js, TypeScript, TailwindCSS, Three.js, Web Audio API' },
          { type: 'output', text: '  [Backend]  : Node.js, Go (Golang), Python FastAPI, PostgreSQL, Redis' },
          { type: 'output', text: '  [DevOps]   : Docker, Kubernetes, AWS, Cloudflare Workers, GitHub Actions' },
          { type: 'output', text: '  [Secret]   : Midnight Coffee Brewing (100% Mastery)' }
        );
        break;

      case 'hop':
        sound.playHop(1.5);
        newLines.push(
          { type: 'success', text: '🦘 *TƯNG TƯNG TƯNG!* Ma Cà Tưng vừa nhảy lên 1 bước cao vút!' },
          { type: 'output', text: '   +1 Hop point added to your ledger!' }
        );
        break;

      case 'coffee':
        sound.playTalisman();
        newLines.push(
          { type: 'ascii', text: '      (  )   (   )  )\n     ) (   )  (  (\n     ( )  (    ) )\n     _____________\n    <_____________> ___\n    |             |/ _ \\\n    |  ROBUSTA   | | | |\n    |   DARK     | |_| |\n    |_____________|\\___/\n    \\___________/' },
          { type: 'success', text: '☕ Ly cà phê Robusta đen đậm đặc 90°C đã sẵn sàng. Trí não hồi phục 100% năng lượng!' }
        );
        break;

      case 'talisman':
        sound.playTalisman();
        newLines.push(
          { type: 'ascii', text: '    .--------------------.\n    |  // ZERO_BUG_PROTO |\n    |--------------------|\n    |  const safe = true;|\n    |  while (coding) {  |\n    |    shipPerfection()|\n    |  }                 |\n    |--------------------|\n    |  ⚡ MACATUNG.DEV ⚡ |\n    \'--------------------\'' },
          { type: 'success', text: '📜 Bùa 0 Bug đã kích hoạt! Bảo vệ bạn khỏi mọi cú sập server.' }
        );
        break;

      case 'slogan':
        newLines.push(
          { type: 'success', text: '🌙 "Code at midnight."' },
          { type: 'output', text: 'When the world is fast asleep, the true creators awaken.' }
        );
        break;

      case 'summon':
      case 'contact':
        newLines.push(
          { type: 'output', text: '📬 TRANSMISSION CHANNELS:' },
          { type: 'output', text: '  • Email    : summon@macatung.dev' },
          { type: 'output', text: '  • GitHub   : github.com/macatung' },
          { type: 'output', text: '  • Telegram : @macatung_dev' },
          { type: 'output', text: 'Scroll down to #contact to cast a direct signal.' }
        );
        break;

      case 'sudo rm -rf bugs':
      case 'rm -rf bugs':
        sound.playSuccess();
        confetti({ particleCount: 50, spread: 70, origin: { y: 0.6 } });
        newLines.push(
          { type: 'success', text: '✨ PURGE IN PROGRESS...' },
          { type: 'output', text: '[OK] Banishing 4,192 null pointer exceptions into the void.' },
          { type: 'output', text: '[OK] Purging race conditions from memory.' },
          { type: 'success', text: '🎉 SUCCESS: 0 bugs remaining. Production is completely clean!' }
        );
        break;

      case 'clear':
        setLines([]);
        setInput('');
        return;

      default:
        newLines.push({
          type: 'error',
          text: `zsh: command not found: "${trimmed}". Type "help" for a list of commands.`,
        });
        break;
    }

    setLines(newLines);
    setInput('');
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      handleCommand(input);
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      if (history.length > 0) {
        const nextIndex = historyIndex === -1 ? history.length - 1 : Math.max(0, historyIndex - 1);
        setHistoryIndex(nextIndex);
        setInput(history[nextIndex]);
      }
    } else if (e.key === 'ArrowDown') {
      e.preventDefault();
      if (historyIndex !== -1) {
        const nextIndex = historyIndex + 1;
        if (nextIndex < history.length) {
          setHistoryIndex(nextIndex);
          setInput(history[nextIndex]);
        } else {
          setHistoryIndex(-1);
          setInput('');
        }
      }
    }
  };

  const copyTerminalOutput = () => {
    const fullText = lines.map((l) => l.text).join('\n');
    navigator.clipboard.writeText(fullText);
    setCopied(true);
    sound.playClick();
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <section id="terminal" className="py-24 relative border-t border-slate-800/60">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto mb-12 space-y-3">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full glass-panel border border-slate-800 text-xs font-mono text-emerald-300">
            <TermIcon className="w-3.5 h-3.5 text-talisman-yellow" />
            <span>// REPL PLAYGROUND</span>
          </div>
          <h2 className="font-display font-extrabold text-3xl sm:text-4xl text-white tracking-tight">
            macatung<span className="text-phantom-mint text-glow-mint">-cli</span>
          </h2>
          <p className="text-slate-400 font-mono text-xs sm:text-sm">
            Trải nghiệm terminal tương tác trực tiếp. Gõ <code className="text-emerald-300 font-bold">help</code> hoặc <code className="text-talisman-yellow font-bold">coffee</code> để khám phá!
          </p>
        </div>

        {/* Terminal Window Box */}
        <div
          className={`rounded-3xl bg-midnight-950 border border-slate-800 shadow-2xl overflow-hidden transition-all duration-300 ${
            isExpanded ? 'max-h-[700px]' : 'max-h-[500px]'
          } flex flex-col`}
        >
          {/* Terminal Title Bar */}
          <div className="px-4 py-3 bg-midnight-900 border-b border-slate-800 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="w-3 h-3 rounded-full bg-slate-700 hover:opacity-100 cursor-pointer" />
              <div className="w-3 h-3 rounded-full bg-slate-700 hover:opacity-100 cursor-pointer" />
              <div className="w-3 h-3 rounded-full bg-emerald-500/80 hover:opacity-100 cursor-pointer" />
              <span className="ml-2 text-xs font-mono text-slate-400 flex items-center gap-1.5">
                <TermIcon className="w-3.5 h-3.5 text-emerald-400" />
                <span>macatung@midnight-sanctuary: ~ (zsh)</span>
              </span>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={copyTerminalOutput}
                className="p-1.5 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
                title="Copy Terminal Logs"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              </button>
              <button
                onClick={() => {
                  sound.playClick();
                  setIsExpanded(!isExpanded);
                }}
                className="p-1.5 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
                title={isExpanded ? 'Thu nhỏ' : 'Phóng to'}
              >
                {isExpanded ? <Minimize2 className="w-3.5 h-3.5" /> : <Maximize2 className="w-3.5 h-3.5" />}
              </button>
            </div>
          </div>

          {/* Terminal Output Area */}
          <div
            className="p-5 overflow-y-auto font-mono text-xs sm:text-sm space-y-1.5 text-slate-300 flex-1 leading-relaxed cursor-text"
            onClick={() => inputRef.current?.focus()}
          >
            {lines.map((line, idx) => {
              if (line.type === 'input') {
                return (
                  <div key={idx} className="text-phantom-mint font-bold pt-1">
                    {line.text}
                  </div>
                );
              }
              if (line.type === 'error') {
                return (
                  <div key={idx} className="text-rose-400">
                    {line.text}
                  </div>
                );
              }
              if (line.type === 'success') {
                return (
                  <div key={idx} className="text-emerald-300 font-semibold">
                    {line.text}
                  </div>
                );
              }
              if (line.type === 'ascii') {
                return (
                  <pre key={idx} className="text-amber-300 font-mono text-[11px] leading-tight select-none">
                    {line.text}
                  </pre>
                );
              }
              return (
                <div key={idx} className="text-slate-300">
                  {line.text}
                </div>
              );
            })}

            {/* Input Row */}
            <div className="flex items-center gap-2 pt-2 text-emerald-400">
              <span className="font-bold select-none">$</span>
              <input
                ref={inputRef}
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="type a command... (e.g. coffee, hop, projects)"
                className="flex-1 bg-transparent text-slate-100 placeholder:text-slate-600 focus:outline-none font-mono text-xs sm:text-sm"
                autoComplete="off"
                spellCheck="false"
              />
              <button
                onClick={() => handleCommand(input)}
                className="p-1 rounded bg-slate-800 text-slate-400 hover:text-emerald-300"
                title="Execute"
              >
                <CornerDownLeft className="w-3.5 h-3.5" />
              </button>
            </div>

            <div ref={terminalEndRef} />
          </div>

          {/* Terminal Quick Hint Bar */}
          <div className="px-4 py-2 bg-midnight-900/60 border-t border-slate-800/80 flex flex-wrap items-center gap-2 text-[11px] font-mono text-slate-500">
            <span className="text-slate-400 font-semibold">Quick click:</span>
            {['help', 'whoami', 'coffee', 'hop', 'projects', 'sudo rm -rf bugs'].map((c) => (
              <button
                key={c}
                onClick={() => handleCommand(c)}
                className="px-2 py-0.5 rounded bg-slate-800/80 hover:bg-emerald-500/20 text-slate-300 hover:text-emerald-300 transition-colors border border-slate-700/50"
              >
                {c}
              </button>
            ))}
          </div>

        </div>

      </div>
    </section>
  );
};
