// resources/js/Components/mascot/MidnightClock.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import Icons from '@/Components/ui/Icons.vue';

const currentTime = ref<Date>(new Date());
const pingMs = ref<number>(14);
let intervalId: number | undefined;

const pad = (n: number) => String(n).padStart(2, '0');

const formattedTime = computed(() => {
  const h = pad(currentTime.value.getHours());
  const m = pad(currentTime.value.getMinutes());
  const s = pad(currentTime.value.getSeconds());
  return `${h}:${m}:${s}`;
});

const isMidnightMode = computed(() => {
  const hours = currentTime.value.getHours();
  return hours >= 0 && hours < 5;
});

const statusBadge = computed(() => {
  if (isMidnightMode.value) {
    return { mode: 'midnight' as const, text: '🌙 Midnight Mode — Maximum Focus & Flow' };
  }
  return { mode: 'daylight' as const, text: '☀️ Daylight Prep — Charging & Rebuilding' };
});

const caffeineLevel = computed(() => {
  const hour = currentTime.value.getHours();
  if (hour >= 1 && hour <= 4) return 100;
  if (hour === 0 || hour === 5) return 85;
  if (hour >= 6 && hour <= 9) return 40;
  if (hour >= 10 && hour <= 17) return 25;
  if (hour >= 18 && hour <= 21) return 50;
  return 75;
});

onMounted(() => {
  intervalId = window.setInterval(() => {
    currentTime.value = new Date();
    // Natural sub-30ms ping
    pingMs.value = Math.max(8, Math.min(32, Math.floor(12 + Math.random() * 6)));
  }, 1000);
});

onUnmounted(() => {
  if (intervalId) clearInterval(intervalId);
});
</script>

<template>
  <div
    class="inline-flex items-center gap-2 px-3 py-1.5 rounded-full glass-panel border border-white/10 shadow-inner text-xs font-mono select-none transition-all hover:border-phantom-mint/30"
    :title="`${statusBadge.text} | Caffeine: ${caffeineLevel}% | Latency: ${pingMs}ms`"
  >
    <!-- Live Pulse & Time (Always Visible) -->
    <div class="flex items-center gap-1.5 whitespace-nowrap">
      <span
        class="w-2 h-2 rounded-full transition-colors flex-shrink-0"
        :class="isMidnightMode ? 'bg-phantom-mint animate-pulse shadow-glow-mint' : 'bg-talisman-gold animate-pulse shadow-glow-talisman'"
      />
      <span class="font-bold text-slate-100 tracking-wider tabular-nums text-[11px] sm:text-xs">
        {{ formattedTime }}
      </span>
    </div>

    <!-- Mode Badge (Hidden on medium screens to keep header compact, visible on 2xl) -->
    <div class="hidden 2xl:flex items-center gap-1 text-[11px] text-slate-300 border-l border-white/10 pl-2 whitespace-nowrap">
      <span v-if="isMidnightMode" class="text-phantom-mint font-semibold">Midnight Mode</span>
      <span v-else class="text-talisman-gold font-semibold">Daylight Prep</span>
    </div>

    <!-- Caffeine Tracker (Hidden on medium/large screens to avoid crowding) -->
    <div class="hidden 2xl:flex items-center gap-1 text-[11px] text-slate-300 border-l border-white/10 pl-2 whitespace-nowrap">
      <Icons name="Coffee" :size="12" class="text-amber-400" />
      <span class="text-amber-300 font-bold tabular-nums">{{ caffeineLevel }}%</span>
    </div>
  </div>
</template>

// src/components/mascot/MidnightClock.tsx
import React, { useState, useEffect } from 'react';
import { Moon, Sun, Coffee, Activity } from 'lucide-react';

export const MidnightClock: React.FC = () => {
  const [time, setTime] = useState<Date>(new Date());
  const [caffeinePercent, setCaffeinePercent] = useState<number>(98);

  useEffect(() => {
    const timer = setInterval(() => {
      const now = new Date();
      setTime(now);
      // Fun dynamic caffeine calculation
      const hours = now.getHours();
      if (hours >= 22 || hours <= 4) {
        setCaffeinePercent(90 + (now.getMinutes() % 10));
      } else {
        setCaffeinePercent(65 + (now.getMinutes() % 20));
      }
    }, 1000);

    return () => clearInterval(timer);
  }, []);

  const hours = time.getHours();
  const isMidnightHours = hours >= 22 || hours <= 5;

  const formatDigits = (n: number) => n.toString().padStart(2, '0');
  const timeString = `${formatDigits(hours)}:${formatDigits(time.getMinutes())}:${formatDigits(time.getSeconds())}`;

  return (
    <div className="flex flex-wrap items-center gap-3 px-3.5 py-1.5 rounded-full glass-panel border border-slate-700/60 shadow-inner text-xs font-mono">
      {/* Live Time */}
      <div className="flex items-center gap-1.5 text-slate-200">
        <span className="relative flex h-2 w-2">
          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-phantom-mint opacity-75"></span>
          <span className="relative inline-flex rounded-full h-2 w-2 bg-phantom-mint"></span>
        </span>
        <span className="font-bold tracking-wider text-phantom-mint">{timeString}</span>
      </div>

      <div className="h-3 w-px bg-slate-700 hidden sm:block" />

      {/* Midnight State Badge */}
      <div className="hidden sm:flex items-center gap-1.5">
        {isMidnightHours ? (
          <span className="flex items-center gap-1 text-emerald-300">
            <Moon className="w-3.5 h-3.5 text-talisman-yellow animate-pulse" />
            <span className="font-semibold text-[11px]">Midnight Code Mode</span>
          </span>
        ) : (
          <span className="flex items-center gap-1 text-amber-300">
            <Sun className="w-3.5 h-3.5 text-amber-400" />
            <span className="font-semibold text-[11px]">Daylight Prep</span>
          </span>
        )}
      </div>

      <div className="h-3 w-px bg-slate-700 hidden md:block" />

      {/* Caffeine Level */}
      <div className="hidden md:flex items-center gap-1.5 text-slate-400">
        <Coffee className="w-3.5 h-3.5 text-amber-400" />
        <span>Caffeine:</span>
        <span className="text-amber-300 font-bold">{caffeinePercent}%</span>
      </div>

      <div className="h-3 w-px bg-slate-700 hidden lg:block" />

      {/* Latency */}
      <div className="hidden lg:flex items-center gap-1 text-slate-400">
        <Activity className="w-3.5 h-3.5 text-cyan-400" />
        <span className="text-cyan-300">12ms</span>
      </div>
    </div>
  );
};
