// resources/js/Components/mascot/TalismanCanvas.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';

interface Particle {
  id: number;
  x: number;
  y: number;
  vx: number;
  vy: number;
  size: number;
  type: 'talisman' | 'firefly' | 'ember';
  rotation: number;
  rotationSpeed: number;
  alpha: number;
  runeText?: string;
}

const canvasRef = ref<HTMLCanvasElement | null>(null);
let animationFrameId: number | null = null;
let particles: Particle[] = [];
let mouseX = -1000;
let mouseY = -1000;
let width = 0;
let height = 0;

const runes = ['0 BUG', '</>', '⚡', 'DEV', '☕', 'HOP', '12AM', '勅令', '安鎮', '靈符'];

const createParticles = (count: number) => {
  particles = [];
  for (let i = 0; i < count; i++) {
    const typeChoice: 'talisman' | 'firefly' | 'ember' = i % 3 === 0 ? 'talisman' : i % 3 === 1 ? 'firefly' : 'ember';
    particles.push({
      id: i,
      x: Math.random() * (width || 800),
      y: Math.random() * (height || 600),
      vx: (Math.random() - 0.5) * 1.2,
      vy: (Math.random() - 0.5) * 1.2 - 0.2, // Slight upward atmospheric drift
      size: typeChoice === 'talisman' ? 24 : typeChoice === 'firefly' ? 4 : 2,
      type: typeChoice,
      rotation: Math.random() * Math.PI * 2,
      rotationSpeed: (Math.random() - 0.5) * 0.02,
      alpha: 0.25 + Math.random() * 0.55,
      runeText: typeChoice === 'talisman' ? runes[i % runes.length] : undefined,
    });
  }
};

const handleResize = () => {
  if (!canvasRef.value) return;
  width = Math.max(0, window.innerWidth);
  height = Math.max(0, window.innerHeight);
  canvasRef.value.width = width;
  canvasRef.value.height = height;

  const count = Math.min(36, Math.max(14, Math.floor(width / 45)));
  if (particles.length === 0 || Math.abs(particles.length - count) > 10) {
    createParticles(count);
  }
};

const handleMouseMove = (e: MouseEvent) => {
  mouseX = e.clientX;
  mouseY = e.clientY;
};

const handleMouseLeave = () => {
  mouseX = -1000;
  mouseY = -1000;
};

const update = () => {
  const margin = 50;
  const repulsionRadius = 120;

  for (let i = 0; i < particles.length; i++) {
    const p = particles[i];

    // 1. Mouse Repulsion Physics
    const dx = p.x - mouseX;
    const dy = p.y - mouseY;
    const dist = Math.sqrt(dx * dx + dy * dy);

    if (dist < repulsionRadius && dist >= 0) {
      const safeDist = Math.max(dist, 0.001);
      const force = (repulsionRadius - dist) / repulsionRadius;
      p.vx += (dx / safeDist) * force * 0.8;
      p.vy += (dy / safeDist) * force * 0.8;
    }

    // 2. Velocity damping & position integration
    p.vx *= 0.98;
    p.vy *= 0.98;
    p.x += p.vx;
    p.y += p.vy;
    p.rotation += p.rotationSpeed;

    // 3. Screen Edge Coordinate Wrap
    if (width > 0 && height > 0) {
      if (p.x < -margin) p.x = width + margin;
      else if (p.x > width + margin) p.x = -margin;

      if (p.y < -margin) p.y = height + margin;
      else if (p.y > height + margin) p.y = -margin;
    }
  }
};

const render = (ctx: CanvasRenderingContext2D) => {
  ctx.clearRect(0, 0, width, height);

  for (let i = 0; i < particles.length; i++) {
    const p = particles[i];
    ctx.save();
    ctx.globalAlpha = p.alpha;

    if (p.type === 'talisman') {
      ctx.translate(p.x, p.y);
      ctx.rotate(p.rotation);

      // Yellow Talisman Paper Body
      ctx.fillStyle = '#ffd166';
      ctx.fillRect(-p.size / 2, -p.size, p.size, p.size * 2);

      // Paper border
      ctx.strokeStyle = 'rgba(230, 57, 70, 0.6)';
      ctx.lineWidth = 0.8;
      ctx.strokeRect(-p.size / 2, -p.size, p.size, p.size * 2);

      // Red Top Seal Dot
      ctx.beginPath();
      ctx.arc(0, -p.size + 4, 1.8, 0, Math.PI * 2);
      ctx.fillStyle = '#ef233c';
      ctx.fill();

      // Rune Inscription
      if (p.runeText) {
        ctx.font = 'bold 8px monospace';
        ctx.fillStyle = '#c9182b';
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';
        ctx.fillText(p.runeText, 0, 2);
      }
    } else if (p.type === 'firefly') {
      // Glowing Firefly (Neon Mint)
      ctx.beginPath();
      ctx.arc(p.x, p.y, p.size, 0, Math.PI * 2);
      ctx.fillStyle = '#00f5a0';
      ctx.shadowColor = '#00f5a0';
      ctx.shadowBlur = 8;
      ctx.fill();
    } else {
      // Golden Ember
      ctx.beginPath();
      ctx.arc(p.x, p.y, p.size, 0, Math.PI * 2);
      ctx.fillStyle = '#ffd166';
      ctx.shadowColor = '#ffd166';
      ctx.shadowBlur = 6;
      ctx.fill();
    }

    ctx.restore();
  }
};

const loop = () => {
  if (!canvasRef.value) return;
  const ctx = canvasRef.value.getContext('2d');
  if (ctx) {
    update();
    render(ctx);
  }
  animationFrameId = requestAnimationFrame(loop);
};

onMounted(() => {
  if (typeof window !== 'undefined') {
    handleResize();
    window.addEventListener('resize', handleResize);
    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('mouseleave', handleMouseLeave);
    animationFrameId = requestAnimationFrame(loop);
  }
});

onUnmounted(() => {
  if (animationFrameId !== null && typeof cancelAnimationFrame === 'function') {
    cancelAnimationFrame(animationFrameId);
    animationFrameId = null;
  }
  if (typeof window !== 'undefined') {
    window.removeEventListener('resize', handleResize);
    window.removeEventListener('mousemove', handleMouseMove);
    window.removeEventListener('mouseleave', handleMouseLeave);
  }
  particles = [];
});
</script>

<template>
  <canvas
    ref="canvasRef"
    class="fixed inset-0 pointer-events-none z-0 w-full h-full"
    aria-hidden="true"
  />
</template>

// src/components/mascot/TalismanCanvas.tsx
import React, { useEffect, useRef } from 'react';

interface Particle {
  x: number;
  y: number;
  size: number;
  speedX: number;
  speedY: number;
  type: 'talisman' | 'firefly' | 'ember';
  rotation: number;
  rotSpeed: number;
  opacity: number;
  pulseSpeed: number;
  color: string;
}

export const TalismanCanvas: React.FC = () => {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    let animationFrameId: number;
    let width = (canvas.width = window.innerWidth);
    let height = (canvas.height = window.innerHeight);

    const handleResize = () => {
      if (!canvas) return;
      width = canvas.width = window.innerWidth;
      height = canvas.height = window.innerHeight;
    };

    window.addEventListener('resize', handleResize);

    // Create subtle particles
    const particleCount = Math.min(24, Math.floor(window.innerWidth / 50));
    const particles: Particle[] = [];

    // Clean tech rune symbols (no Chinese characters)
    const runeSymbols = ['0 BUG', '</>', '⚡', 'DEV', '☕', 'HOP', '12AM'];

    for (let i = 0; i < particleCount; i++) {
      const isTalisman = i % 4 === 0;
      const isEmber = i % 4 === 1;

      particles.push({
        x: Math.random() * width,
        y: Math.random() * height,
        size: isTalisman ? Math.random() * 6 + 12 : Math.random() * 1.5 + 1.2,
        speedX: (Math.random() - 0.5) * 0.3,
        speedY: isTalisman ? (Math.random() * 0.25 + 0.1) : -(Math.random() * 0.3 + 0.08),
        type: isTalisman ? 'talisman' : isEmber ? 'ember' : 'firefly',
        rotation: Math.random() * Math.PI * 2,
        rotSpeed: (Math.random() - 0.5) * 0.01,
        opacity: Math.random() * 0.35 + 0.15,
        pulseSpeed: Math.random() * 0.015 + 0.008,
        color: isTalisman
          ? '#ffd166'
          : isEmber
          ? '#ff4d6d'
          : Math.random() > 0.5
          ? '#00f5a0'
          : '#00d2ff',
      });
    }

    let mouseX = -1000;
    let mouseY = -1000;

    const handleMouseMove = (e: MouseEvent) => {
      mouseX = e.clientX;
      mouseY = e.clientY;
    };

    window.addEventListener('mousemove', handleMouseMove);

    // Render loop
    let tick = 0;
    const render = () => {
      tick++;
      ctx.clearRect(0, 0, width, height);

      particles.forEach((p, idx) => {
        // Move
        p.x += p.speedX;
        p.y += p.speedY;
        p.rotation += p.rotSpeed;

        // Subtle mouse repulsion
        const dx = p.x - mouseX;
        const dy = p.y - mouseY;
        const dist = Math.sqrt(dx * dx + dy * dy);
        if (dist < 100) {
          const angle = Math.atan2(dy, dx);
          const force = (100 - dist) / 100;
          p.x += Math.cos(angle) * force * 1.2;
          p.y += Math.sin(angle) * force * 1.2;
        }

        // Screen wrap
        if (p.x < -30) p.x = width + 20;
        if (p.x > width + 30) p.x = -20;
        if (p.y < -30) p.y = height + 20;
        if (p.y > height + 30) p.y = -20;

        // Draw Talisman or Firefly
        ctx.save();
        ctx.translate(p.x, p.y);
        ctx.rotate(p.rotation);

        if (p.type === 'talisman') {
          // Yellow paper talisman
          const w = p.size;
          const h = p.size * 2.2;
          const currentOpacity = p.opacity * (0.85 + Math.sin(tick * p.pulseSpeed) * 0.15);

          ctx.globalAlpha = currentOpacity;

          // Paper body
          ctx.fillStyle = '#eed060';
          ctx.fillRect(-w / 2, -h / 2, w, h);

          // Red border & header
          ctx.strokeStyle = '#b91c1c';
          ctx.lineWidth = 0.8;
          ctx.strokeRect(-w / 2 + 1, -h / 2 + 1, w - 2, h - 2);

          // Code icon circle
          ctx.fillStyle = '#b91c1c';
          ctx.beginPath();
          ctx.arc(0, -h / 2 + 4, 1.8, 0, Math.PI * 2);
          ctx.fill();

          // Symbol
          const symbol = runeSymbols[idx % runeSymbols.length];
          ctx.fillStyle = '#7f1d1d';
          ctx.font = `bold ${Math.max(5.5, Math.floor(w * 0.32))}px monospace`;
          ctx.textAlign = 'center';
          ctx.fillText(symbol, 0, 2);

        } else {
          // Subtle firefly
          const currentOpacity = p.opacity * (0.5 + Math.sin(tick * p.pulseSpeed * 2) * 0.3);
          ctx.globalAlpha = currentOpacity;

          const glowRad = p.size * 2.5;
          const grad = ctx.createRadialGradient(0, 0, 0, 0, 0, glowRad);
          grad.addColorStop(0, p.color);
          grad.addColorStop(1, 'transparent');

          ctx.fillStyle = grad;
          ctx.beginPath();
          ctx.arc(0, 0, glowRad, 0, Math.PI * 2);
          ctx.fill();

          ctx.fillStyle = '#ffffff';
          ctx.beginPath();
          ctx.arc(0, 0, p.size * 0.6, 0, Math.PI * 2);
          ctx.fill();
        }

        ctx.restore();
      });

      animationFrameId = requestAnimationFrame(render);
    };

    render();

    return () => {
      window.removeEventListener('resize', handleResize);
      window.removeEventListener('mousemove', handleMouseMove);
      cancelAnimationFrame(animationFrameId);
    };
  }, []);

  return (
    <canvas
      ref={canvasRef}
      className="fixed inset-0 pointer-events-none z-0"
      style={{ opacity: 0.6 }}
    />
  );
};
