// resources/js/Components/layout/Navbar.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import MidnightClock from '@/Components/mascot/MidnightClock.vue';
import MiniMascotLogo from '@/Components/mascot/MiniMascotLogo.vue';
import SoundToggle from '@/Components/layout/SoundToggle.vue';
import Icons from '@/Components/ui/Icons.vue';
import { sound } from '@/audio/soundEffects';

interface NavItem {
  label: string;
  href: string;
  badge?: string;
}

const navLinks: NavItem[] = [
  { label: 'Dự Án', href: '#projects' },
  { label: 'Kỹ Năng', href: '#skills' },
  { label: 'Kinh Nghiệm', href: '#experience' },
  { label: 'Triết Lý', href: '#about' },
  { label: 'Bùa Dev', href: '#talisman', badge: 'HOT' },
  { label: 'Terminal', href: '#terminal', badge: 'CLI' },
];

const isScrolled = ref(false);
const isMobileDrawerOpen = ref(false);

const handleScroll = () => {
  if (typeof window !== 'undefined') {
    isScrolled.value = window.scrollY > 40;
  }
};

const toggleMobileDrawer = () => {
  isMobileDrawerOpen.value = !isMobileDrawerOpen.value;
  sound.playClick();
};

const closeMobileDrawer = () => {
  isMobileDrawerOpen.value = false;
};

const handleNavClick = () => {
  closeMobileDrawer();
  sound.playClick();
};

onMounted(() => {
  if (typeof window !== 'undefined') {
    window.addEventListener('scroll', handleScroll, { passive: true });
  }
});

onUnmounted(() => {
  if (typeof window !== 'undefined') {
    window.removeEventListener('scroll', handleScroll);
  }
});
</script>

<template>
  <header
    class="sticky top-0 z-40 transition-all duration-300 border-b"
    :class="isScrolled
      ? 'bg-midnight-950/95 backdrop-blur-xl border-white/10 shadow-xl shadow-black/50 py-2.5'
      : 'bg-midnight-950/80 backdrop-blur-md border-white/5 py-3.5'"
  >
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between gap-4">
      
      <!-- Brand Logo with Animated Hopping Mascot -->
      <a
        href="#hero"
        class="flex items-center gap-3 select-none group focus:outline-none flex-shrink-0"
        @click="sound.playHop(1.3)"
      >
        <!-- Animated Mini Vector Mascot Badge -->
        <MiniMascotLogo size="md" :animated="true" />

        <div class="flex flex-col">
          <span class="font-display font-bold text-base sm:text-lg tracking-tight text-white flex items-center group-hover:text-phantom-mint transition-colors">
            macatung<span class="text-phantom-mint">.dev</span>
          </span>
          <span class="text-[10px] font-mono text-slate-400 -mt-0.5 tracking-wider hidden sm:inline-block">
            Code at midnight
          </span>
        </div>
      </a>

      <!-- Desktop Nav Items (Centered & Clean with whitespace-nowrap) -->
      <nav class="hidden lg:flex items-center gap-1 xl:gap-2 px-3 py-1.5 rounded-2xl glass-panel border border-white/5" aria-label="Main Navigation">
        <a
          v-for="item in navLinks"
          :key="item.href"
          :href="item.href"
          class="px-3 py-1.5 rounded-xl text-xs xl:text-sm font-sans font-medium text-slate-300 hover:text-white hover:bg-white/10 transition-all relative flex items-center gap-1.5 whitespace-nowrap focus:outline-none"
          @click="sound.playClick()"
        >
          <span>{{ item.label }}</span>
          <span
            v-if="item.badge"
            class="text-[9px] font-mono px-1.5 py-0.5 rounded font-bold uppercase tracking-wider whitespace-nowrap"
            :class="item.badge === 'HOT'
              ? 'bg-amber-500/20 text-talisman-gold border border-talisman-gold/40'
              : 'bg-purple-500/20 text-purple-300 border border-purple-400/40'"
          >
            {{ item.badge }}
          </span>
        </a>
      </nav>

      <!-- Right Actions: Clock, Sound Toggle, CTA & Mobile Toggle -->
      <div class="flex items-center gap-2 sm:gap-3 flex-shrink-0">
        <!-- Compact Midnight Clock -->
        <MidnightClock class="hidden md:inline-flex" />

        <!-- Sound Toggle -->
        <SoundToggle />

        <!-- High-Impact Primary CTA Button -->
        <a
          href="#contact"
          class="hidden sm:inline-flex px-4 py-2 rounded-xl bg-phantom-mint text-midnight-950 text-xs font-mono font-extrabold hover:brightness-110 active:scale-95 transition-all shadow-glow-mint min-h-[40px] items-center gap-1.5 whitespace-nowrap"
          @click="sound.playTalisman()"
        >
          <span>Triệu Hồi</span>
          <span>⚡</span>
        </a>

        <!-- Mobile Menu Toggle Button -->
        <button
          type="button"
          class="lg:hidden p-2 rounded-xl text-slate-300 hover:text-white hover:bg-white/5 transition-colors min-h-[40px] min-w-[40px] flex items-center justify-center border border-white/10"
          :aria-expanded="isMobileDrawerOpen"
          aria-label="Mở Menu Điều Hướng"
          @click="toggleMobileDrawer"
        >
          <Icons v-if="!isMobileDrawerOpen" name="Menu" :size="20" />
          <Icons v-else name="X" :size="20" />
        </button>
      </div>
    </div>

    <!-- Mobile Drawer Overlay & Sheet -->
    <div
      v-if="isMobileDrawerOpen"
      class="fixed inset-0 z-50 bg-midnight-950/95 backdrop-blur-2xl lg:hidden flex flex-col p-6 overflow-y-auto animate-fadeIn"
      role="dialog"
      aria-modal="true"
    >
      <!-- Mobile Drawer Header -->
      <div class="flex items-center justify-between pb-6 border-b border-white/10">
        <a
          href="#hero"
          class="flex items-center gap-3"
          @click="handleNavClick"
        >
          <MiniMascotLogo size="sm" :animated="true" />
          <span class="font-display font-bold text-lg text-white">
            macatung<span class="text-phantom-mint">.dev</span>
          </span>
        </a>
        <button
          type="button"
          class="p-2 rounded-xl text-slate-400 hover:text-white bg-white/5 min-h-[44px] min-w-[44px] flex items-center justify-center"
          aria-label="Đóng Menu"
          @click="closeMobileDrawer"
        >
          <Icons name="X" :size="20" />
        </button>
      </div>

      <!-- Mobile Clock Pill -->
      <div class="py-4 flex justify-center">
        <MidnightClock />
      </div>

      <!-- Mobile Navigation Links -->
      <nav class="flex flex-col gap-2 py-4" aria-label="Mobile Navigation">
        <a
          v-for="item in navLinks"
          :key="item.href"
          :href="item.href"
          class="text-base font-medium text-slate-200 hover:text-phantom-mint py-3 px-4 rounded-xl hover:bg-white/5 transition-all flex items-center justify-between min-h-[44px]"
          @click="handleNavClick"
        >
          <span class="font-sans">{{ item.label }}</span>
          <span
            v-if="item.badge"
            class="text-[10px] font-mono px-2 py-0.5 rounded font-bold uppercase"
            :class="item.badge === 'HOT' ? 'bg-amber-500/20 text-talisman-gold' : 'bg-purple-500/20 text-purple-300'"
          >
            {{ item.badge }}
          </span>
        </a>
      </nav>

      <!-- Mobile Drawer Footer Actions -->
      <div class="mt-auto pt-6 border-t border-white/10 flex flex-col gap-3">
        <a
          href="#contact"
          class="w-full py-3.5 rounded-2xl bg-phantom-mint text-midnight-950 font-display font-extrabold text-sm text-center shadow-glow-mint min-h-[48px] flex items-center justify-center gap-2"
          @click="handleNavClick"
        >
          <span>Triệu Hồi Ngay 🚀</span>
        </a>
      </div>
    </div>
  </header>
</template>

// src/components/layout/Navbar.tsx
import React, { useState, useEffect } from 'react';
import { sound } from '../../audio/soundEffects';
import { SoundToggle } from './SoundToggle';
import { MidnightClock } from '../mascot/MidnightClock';
import { Terminal, Sparkles, Menu, X, Code2, Layers, Compass, Mail } from 'lucide-react';

export const Navbar: React.FC = () => {
  const [scrolled, setScrolled] = useState<boolean>(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState<boolean>(false);

  useEffect(() => {
    const handleScroll = () => {
      setScrolled(window.scrollY > 20);
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const navItems = [
    { label: 'Origin', href: '#about', icon: Compass },
    { label: 'Projects', href: '#projects', icon: Layers },
    { label: 'Skills', href: '#skills', icon: Code2 },
    { label: 'Experience', href: '#experience', icon: Sparkles },
    { label: 'Terminal', href: '#terminal', icon: Terminal },
    { label: 'Bùa Dev', href: '#talisman-gen', icon: Sparkles },
    { label: 'Summon Me', href: '#contact', icon: Mail, primary: true },
  ];

  const handleNavClick = (href: string) => {
    sound.playClick();
    setMobileMenuOpen(false);
    const element = document.querySelector(href);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  };

  return (
    <header
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        scrolled
          ? 'py-3 bg-midnight-950/80 backdrop-blur-xl border-b border-slate-800/80 shadow-2xl shadow-black/60'
          : 'py-5 bg-transparent'
      }`}
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between gap-4">
          {/* Logo & Slogan */}
          <a
            href="#"
            onClick={(e) => {
              e.preventDefault();
              sound.playHop();
              window.scrollTo({ top: 0, behavior: 'smooth' });
            }}
            className="flex items-center gap-3 group focus:outline-none"
          >
            {/* Mini Hopping Mascot Icon */}
            <div className="relative w-10 h-10 rounded-xl bg-midnight-900 border border-emerald-500/40 p-1 flex items-center justify-center group-hover:border-phantom-mint transition-all shadow-glow-mint overflow-hidden">
              <svg
                viewBox="0 0 100 110"
                className="w-full h-full animate-hop group-hover:scale-110 transition-transform"
                fill="none"
              >
                {/* Hat */}
                <path d="M25 28 C25 12 75 12 75 28 L85 36 L15 36 Z" fill="#1e293b" stroke="#ffd166" strokeWidth="3" />
                <circle cx="50" cy="22" r="5" fill="#e63946" stroke="#ffd166" strokeWidth="2" />
                <line x1="50" y1="17" x2="50" y2="4" stroke="#00f5a0" strokeWidth="3" strokeLinecap="round" />
                {/* Head */}
                <circle cx="50" cy="62" r="32" fill="#d8f3dc" stroke="#00f5a0" strokeWidth="3" />
                {/* Eyes */}
                <circle cx="38" cy="60" r="5" fill="#00f5d4" />
                <circle cx="62" cy="60" r="5" fill="#00f5d4" />
                <circle cx="36.5" cy="58.5" r="1.5" fill="#ffffff" />
                <circle cx="60.5" cy="58.5" r="1.5" fill="#ffffff" />
                {/* Cheeks */}
                <ellipse cx="32" cy="70" rx="4" ry="2.5" fill="#ff0054" opacity="0.5" />
                <ellipse cx="68" cy="70" rx="4" ry="2.5" fill="#ff0054" opacity="0.5" />
                {/* Fangs Mouth */}
                <path d="M44 72 Q50 78 56 72" stroke="#0f172a" strokeWidth="2.5" fill="none" strokeLinecap="round" />
                {/* Talisman on Head */}
                <rect x="42" y="32" width="16" height="34" rx="2" fill="#ffd166" stroke="#c9182b" strokeWidth="1.5" />
                <circle cx="50" cy="38" r="3" fill="#c9182b" />
                <text x="50" y="55" textAnchor="middle" fill="#8f0e1d" fontSize="6.5" fontFamily="monospace" fontWeight="bold">0BUG</text>
              </svg>
            </div>

            <div>
              <div className="flex items-center gap-2">
                <span className="font-display font-bold text-lg tracking-tight text-white group-hover:text-phantom-mint transition-colors">
                  macatung<span className="text-phantom-mint">.dev</span>
                </span>
                <span className="px-1.5 py-0.5 rounded text-[10px] font-mono uppercase font-extrabold bg-emerald-500/10 text-emerald-300 border border-emerald-500/30 hidden sm:inline-block">
                  v2.0
                </span>
              </div>
              <p className="text-[11px] font-mono text-slate-400 -mt-0.5 tracking-wide flex items-center gap-1">
                <span className="text-talisman-yellow">⚡</span>
                <span className="italic">Code at midnight</span>
              </p>
            </div>
          </a>

          {/* Desktop Nav Links */}
          <nav className="hidden lg:flex items-center gap-1 xl:gap-2">
            {navItems.map((item) => {
              const Icon = item.icon;
              return (
                <button
                  key={item.label}
                  onClick={() => handleNavClick(item.href)}
                  className={`px-3 py-1.5 rounded-xl text-xs font-mono transition-all duration-200 flex items-center gap-1.5 ${
                    item.primary
                      ? 'bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-400 hover:to-teal-400 text-midnight-950 font-bold shadow-glow-mint ml-2'
                      : 'text-slate-300 hover:text-white hover:bg-slate-800/60'
                  }`}
                >
                  <Icon className={`w-3.5 h-3.5 ${item.primary ? 'text-midnight-950' : 'text-slate-400'}`} />
                  <span>{item.label}</span>
                </button>
              );
            })}
          </nav>

          {/* Right utilities: Midnight Clock & Sound FX */}
          <div className="flex items-center gap-2 sm:gap-3">
            <MidnightClock />
            <SoundToggle />

            {/* Mobile Menu Button */}
            <button
              onClick={() => {
                sound.playClick();
                setMobileMenuOpen(!mobileMenuOpen);
              }}
              className="lg:hidden p-2 rounded-xl bg-slate-900 border border-slate-700 text-slate-300 hover:text-white"
              aria-label="Open Mobile Menu"
            >
              {mobileMenuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
            </button>
          </div>
        </div>
      </div>

      {/* Mobile Drawer */}
      {mobileMenuOpen && (
        <div className="lg:hidden mt-3 px-4 pt-2 pb-6 bg-midnight-950/95 backdrop-blur-2xl border-b border-slate-800 animate-fadeIn">
          <div className="flex flex-col gap-2">
            {navItems.map((item) => {
              const Icon = item.icon;
              return (
                <button
                  key={item.label}
                  onClick={() => handleNavClick(item.href)}
                  className={`w-full text-left px-4 py-3 rounded-xl text-sm font-mono flex items-center justify-between ${
                    item.primary
                      ? 'bg-emerald-500 text-midnight-950 font-bold shadow-glow-mint'
                      : 'bg-slate-900/50 text-slate-200 hover:bg-slate-800'
                  }`}
                >
                  <div className="flex items-center gap-2.5">
                    <Icon className="w-4 h-4" />
                    <span>{item.label}</span>
                  </div>
                  <span className="text-xs text-slate-500 font-mono">→</span>
                </button>
              );
            })}
          </div>
        </div>
      )}
    </header>
  );
};
