// resources/js/Components/layout/SoundToggle.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { sound } from '@/audio/soundEffects';
import Icons from '@/Components/ui/Icons.vue';

const isMuted = ref(false);

onMounted(() => {
  isMuted.value = sound.isMuted();
});

const handleToggle = () => {
  isMuted.value = sound.toggleMute();
};
</script>

<template>
  <button
    type="button"
    class="px-3 py-1.5 rounded-xl border text-xs font-mono flex items-center gap-2 transition-all select-none min-h-[44px] min-w-[44px] justify-center focus:outline-none focus:ring-2 focus:ring-phantom-mint/50"
    :class="!isMuted
      ? 'border-phantom-mint/40 bg-phantom-mint/10 text-phantom-mint hover:bg-phantom-mint/20 shadow-glow-mint'
      : 'border-white/10 bg-midnight-900/80 text-slate-400 hover:text-slate-200 hover:border-white/20'"
    :aria-label="isMuted ? 'Enable sound' : 'Disable sound'"
    :title="isMuted ? 'Enable sound effects' : 'Disable sound effects'"
    @click="handleToggle"
  >
    <!-- Equalizer animation when audio is active -->
    <div v-if="!isMuted" class="flex items-center gap-0.5 h-3.5">
      <span class="w-0.5 bg-phantom-mint rounded-full animate-[pulse_0.8s_ease-in-out_infinite] h-2.5" />
      <span class="w-0.5 bg-phantom-mint rounded-full animate-[pulse_0.6s_ease-in-out_infinite_0.2s] h-3.5" />
      <span class="w-0.5 bg-phantom-mint rounded-full animate-[pulse_1.0s_ease-in-out_infinite_0.4s] h-2" />
    </div>

    <!-- Muted icon when audio is disabled -->
    <Icons v-else name="VolumeX" :size="15" class="text-slate-400" />

    <span class="font-bold hidden sm:inline">{{ isMuted ? 'SFX: OFF' : 'SFX: ON' }}</span>
  </button>
</template>

// src/components/layout/SoundToggle.tsx
import React, { useState } from 'react';
import { sound } from '../../audio/soundEffects';
import { Volume2, VolumeX } from 'lucide-react';

export const SoundToggle: React.FC = () => {
  const [isMuted, setIsMuted] = useState<boolean>(sound.isMuted());

  const handleToggle = () => {
    const nextState = sound.toggleMute();
    setIsMuted(nextState);
  };

  return (
    <button
      onClick={handleToggle}
      className={`p-2 rounded-xl border transition-all duration-200 flex items-center justify-center ${
        isMuted
          ? 'bg-slate-900/60 border-slate-700/60 text-slate-400 hover:text-slate-200'
          : 'bg-emerald-950/40 border-emerald-500/40 text-emerald-300 shadow-glow-mint'
      }`}
      title={isMuted ? 'Bật âm thanh (Sound Effects: OFF)' : 'Tắt âm thanh (Sound Effects: ON)'}
      aria-label="Toggle Sound Effects"
    >
      {isMuted ? (
        <VolumeX className="w-4 h-4" />
      ) : (
        <div className="flex items-center gap-1">
          <Volume2 className="w-4 h-4 animate-pulse" />
          <span className="text-[10px] font-mono font-bold hidden sm:inline">SFX</span>
        </div>
      )}
    </button>
  );
};
