// resources/js/Components/about/AboutSection.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { developerStats } from '@/data/experienceData';
import Icons from '@/Components/ui/Icons.vue';
import { sound } from '@/audio/soundEffects';

interface Props {
  stats?: {
    total_pageviews?: number;
    unique_visitors?: number;
    total_inquiries?: number;
    total_hops?: number;
    total_projects?: number;
  };
}

const props = withDefaults(defineProps<Props>(), {
  stats: () => ({}),
});

type ManifestoTabId = 'philosophy' | 'day-night' | 'craftsmanship';

const activeTab = ref<ManifestoTabId>('philosophy');

const tabs = [
  {
    id: 'philosophy',
    title: 'Triết Lý 00:00 AM',
    subtitle: 'Khi cả thành phố chìm vào giấc ngủ, thế giới của dòng code mới thực sự bừng tỉnh.',
    content: 'Không có tiếng thông báo Slack, không có họp hành ngắt quãng. Chỉ có âm thanh gõ phím, ly Robusta đậm đà và dòng chảy tư duy thuần khiết.',
    icon: 'Moon',
    badge: 'Ultra-Flow'
  },
  {
    id: 'day-night',
    title: 'Day vs Night Developer',
    subtitle: 'Ban ngày bảo trì hệ thống — Ban đêm kiến tạo tương lai.',
    content: 'Ban ngày là giao tiếp, đồng bộ và lập kế hoạch. Ban đêm là thời khắc của kiến trúc, thuật toán tối ưu và những sáng tạo vượt bậc.',
    icon: 'Sun',
    badge: 'Dual Mindset'
  },
  {
    id: 'craftsmanship',
    title: 'Khắc Bùa Chất Lượng',
    subtitle: 'Mỗi dòng mã là một đạo bùa chú trừ khử bug tận gốc.',
    content: 'Không chấp nhận sự cẩu thả. Mọi API đều phải chuẩn chỉ, mọi UI đều phải mượt mà 60 FPS, và mọi test suite đều phải pass 100% trước khi deploy.',
    icon: 'Shield',
    badge: 'Craftsmanship'
  }
];

const setTab = (id: ManifestoTabId) => {
  activeTab.value = id;
  sound.playClick();
};

const activeTabContent = computed(() => {
  return tabs.find((t) => t.id === activeTab.value) || tabs[0];
});

const handleTabKeydown = (e: KeyboardEvent) => {
  const currentIndex = tabs.findIndex((t) => t.id === activeTab.value);
  if (e.key === 'ArrowRight') {
    e.preventDefault();
    const nextIndex = (currentIndex + 1) % tabs.length;
    setTab(tabs[nextIndex].id as ManifestoTabId);
  } else if (e.key === 'ArrowLeft') {
    e.preventDefault();
    const prevIndex = (currentIndex - 1 + tabs.length) % tabs.length;
    setTab(tabs[prevIndex].id as ManifestoTabId);
  } else if (e.key === 'Home') {
    e.preventDefault();
    setTab(tabs[0].id as ManifestoTabId);
  } else if (e.key === 'End') {
    e.preventDefault();
    setTab(tabs[tabs.length - 1].id as ManifestoTabId);
  }
};

const displayStats = computed(() => {
  if (props.stats && props.stats.total_pageviews !== undefined) {
    return [
      {
        value: `${(props.stats.total_pageviews || 0).toLocaleString('vi-VN')}+`,
        label: 'Tổng Lượt Truy Cập Live',
        iconName: 'Eye',
        unit: 'Views',
        description: 'Pageviews ghi nhận bởi Analytics',
      },
      {
        value: `${props.stats.total_projects || 6}`,
        label: 'Dự Án Đang Chạy',
        iconName: 'Layers',
        unit: 'Active',
        description: 'Sản phẩm kỹ thuật trong CMS',
      },
      {
        value: `${props.stats.total_hops || 0}`,
        label: 'Lượt Nhảy Linh Vật',
        iconName: 'Zap',
        unit: 'Hops',
        description: 'Tương tác vật lý Ma Cà Tưng',
      },
      {
        value: '99.9%',
        label: 'Tỷ Lệ Sẵn Sàng 00:00 AM',
        iconName: 'Shield',
        unit: 'SLA',
        description: 'Zero Downtime Architecture',
      },
    ];
  }
  return developerStats;
});

const pillars = [
  {
    icon: 'Moon',
    title: 'Vùng Tĩnh Lặng (Ultra-Flow)',
    desc: 'Tập trung tuyệt đối vào giải quyết core logic, không bị gián đoạn bởi xao nhãng.',
  },
  {
    icon: 'Shield',
    title: 'Kiến Trúc & Type-Safety',
    desc: 'TypeScript nghiêm ngặt 100%, cấu trúc phân tán chuẩn SOLID, loại bỏ runtime crash.',
  },
  {
    icon: 'Zap',
    title: 'Tối Ưu Tốc Độ Thực Chiến',
    desc: 'Độ trễ phản hồi sub-millisecond, giao diện 60 FPS mượt mà và khả năng chịu tải cao.',
  },
];
</script>

<template>
  <section id="about" class="scroll-mt-24 w-full py-16 sm:py-20 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-left">
    <!-- Header -->
    <div class="flex flex-col items-start mb-10">
      <span class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-phantom-mint text-xs font-mono mb-3 whitespace-nowrap select-none shadow-glow-mint">
        🌙 Developer Origin & Principles
      </span>
      <h2 class="text-3xl sm:text-4xl lg:text-5xl font-display font-extrabold text-white tracking-tight">
        Triết Lý & <span class="text-transparent bg-clip-text bg-gradient-to-r from-phantom-mint via-phantom-cyan to-talisman-gold">Bản Lĩnh Đêm</span>
      </h2>
      <p class="text-sm sm:text-base text-slate-400 mt-2 max-w-2xl font-sans">
        Những con số thực chiến và nguyên tắc kỹ thuật được tôi luyện qua hàng ngàn đêm đối mặt với màn hình đen.
      </p>
    </div>

    <!-- 4 Developer Stat Cards -->
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-5 mb-10">
      <div
        v-for="stat in displayStats"
        :key="stat.label"
        class="p-5 sm:p-6 rounded-2xl glass-panel border border-white/[0.08] hover:border-phantom-mint/30 transition-all duration-300 select-none hover:shadow-lg hover:shadow-black/40 group"
      >
        <div class="flex items-center justify-between mb-3">
          <div class="w-10 h-10 rounded-xl bg-midnight-900 border border-white/10 flex items-center justify-center text-phantom-mint group-hover:scale-110 transition-transform">
            <Icons :name="stat.iconName || 'Zap'" :size="18" />
          </div>
          <span v-if="stat.unit" class="text-[10px] font-mono uppercase tracking-wider text-slate-400 px-2 py-0.5 rounded bg-white/5 whitespace-nowrap border border-white/5 font-semibold">
            {{ stat.unit }}
          </span>
        </div>
        <div class="text-3xl font-display font-extrabold text-white mb-1 tracking-tight whitespace-nowrap group-hover:text-phantom-mint transition-colors">
          {{ stat.value }}
        </div>
        <div class="text-sm font-semibold text-slate-200 mb-1 tracking-tight">{{ stat.label }}</div>
        <p class="text-xs font-mono text-slate-400 font-sans leading-relaxed break-words tracking-tight">{{ stat.description }}</p>
      </div>
    </div>

    <!-- Interactive 3-Tab Developer Manifesto -->
    <div class="mb-10 rounded-3xl glass-panel border border-white/10 p-6 sm:p-8 relative overflow-hidden">
      <!-- Ambient Glow Blur -->
      <div class="absolute -top-20 -right-20 w-64 h-64 bg-phantom-mint/5 rounded-full blur-3xl pointer-events-none" />

      <!-- Tabs Header Pills -->
      <div
        class="flex items-center gap-2 mb-6 border-b border-white/10 pb-4 overflow-x-auto no-scrollbar"
        role="tablist"
        @keydown="handleTabKeydown"
      >
        <button
          v-for="tab in tabs"
          :key="tab.id"
          type="button"
          role="tab"
          :aria-selected="activeTab === tab.id"
          tabindex="0"
          class="px-4 py-2.5 rounded-xl text-xs sm:text-sm font-display font-bold transition-all min-h-[42px] shrink-0 flex items-center gap-2 border whitespace-nowrap focus:outline-none focus:ring-2 focus:ring-phantom-mint"
          :class="activeTab === tab.id
            ? 'bg-phantom-mint text-midnight-950 border-phantom-mint shadow-glow-mint'
            : 'bg-midnight-900/80 text-slate-400 border-white/5 hover:border-white/20 hover:text-white'"
          @click="setTab(tab.id as ManifestoTabId)"
        >
          <Icons :name="tab.icon" :size="16" />
          <span>{{ tab.title }}</span>
          <span
            class="text-[10px] font-mono px-1.5 py-0.2 rounded"
            :class="activeTab === tab.id ? 'bg-midnight-950/20 text-midnight-950 font-extrabold' : 'bg-white/5 text-slate-400'"
          >
            {{ tab.badge }}
          </span>
        </button>
      </div>

      <!-- Active Tab Content Panel -->
      <div class="space-y-3">
        <h3 class="text-xl sm:text-2xl font-display font-extrabold text-white">
          {{ activeTabContent.title }}
        </h3>
        <p class="text-sm font-mono text-phantom-mint font-semibold">
          {{ activeTabContent.subtitle }}
        </p>
        <p class="text-sm sm:text-base text-slate-300 font-sans leading-relaxed pt-2">
          {{ activeTabContent.content }}
        </p>
      </div>
    </div>

    <!-- Bio Origin Story Card & 3 Architectural Pillars Grid -->
    <div class="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch">
      <!-- Bio Origin Card (5 Columns) -->
      <div class="about-bio-card glass-panel lg:col-span-5 p-6 sm:p-7 rounded-2xl border border-white/10 flex flex-col justify-between relative overflow-hidden bg-gradient-to-b from-midnight-900/90 to-midnight-950">
        <div class="relative z-10">
          <div class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-talisman-gold/10 text-talisman-gold border border-talisman-gold/30 text-xs font-mono mb-4 font-bold">
            ⚡ The Midnight Architect
          </div>
          <h3 class="font-display font-bold text-white text-xl mb-1">
            Senior Fullstack & AI Agent Architect
          </h3>
          <p class="text-xs font-mono text-phantom-mint mb-3">
            🏆 Giải Quốc Gia Tin Học · 8+ Năm Thực Chiến Hệ Thống Tải Cao
          </p>
          <p class="text-slate-300 text-sm leading-relaxed font-sans mb-4">
            Chuyên sâu kiến trúc hệ thống backend tải cao, nền tảng viễn thông GIS/NMS và thiết kế các hệ sinh thái <strong>Multi-Agent AI tự trị</strong> thay thế quy trình Customer Service truyền thống 24/7 với độ chính xác > 92%.
          </p>
        </div>
        <div class="pt-4 border-t border-white/5 flex items-center justify-between text-xs font-mono text-slate-400 relative z-10">
          <span>📍 Ho Chi Minh City / Remote</span>
          <span class="text-phantom-mint font-bold">⚡ Zero Downtime Pledge</span>
        </div>
      </div>

      <!-- 3 Architectural Pillar Cards (7 Columns) -->
      <div class="lg:col-span-7 grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div
          v-for="(pillar, i) in pillars"
          :key="pillar.title"
          class="p-5 rounded-2xl glass-panel border border-white/[0.08] hover:border-phantom-mint/30 transition-colors flex flex-col justify-between"
        >
          <div>
            <div class="flex items-center justify-between mb-3">
              <div class="w-9 h-9 rounded-xl bg-midnight-900 border border-white/10 flex items-center justify-center text-phantom-mint">
                <Icons :name="pillar.icon" :size="18" />
              </div>
              <span class="text-xs font-mono font-bold text-slate-500">0{{ i + 1 }}</span>
            </div>
            <h4 class="font-display font-bold text-white text-sm sm:text-base mb-1.5">{{ pillar.title }}</h4>
            <p class="text-xs text-slate-400 font-sans leading-relaxed">{{ pillar.desc }}</p>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

// src/components/about/AboutSection.tsx
import React, { useState } from 'react';
import { developerStats } from '../../data/experienceData';
import { sound } from '../../audio/soundEffects';
import { Moon, Sun, Coffee, Zap, Shield, Bug, Sparkles, Code } from 'lucide-react';

export const AboutSection: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'manifesto' | 'day_vs_night' | 'values'>('manifesto');

  const statIcons: Record<string, React.ReactNode> = {
    Coffee: <Coffee className="w-5 h-5 text-amber-400" />,
    Bug: <Bug className="w-5 h-5 text-rose-400" />,
    Zap: <Zap className="w-5 h-5 text-phantom-mint" />,
    Moon: <Moon className="w-5 h-5 text-talisman-yellow" />,
  };

  return (
    <section id="about" className="py-24 relative border-t border-slate-800/80 bg-midnight-950/40">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full glass-panel border border-slate-700 text-xs font-mono text-emerald-300">
            <Sparkles className="w-3.5 h-3.5 text-talisman-yellow" />
            <span>// ORIGIN & PHILOSOPHY</span>
          </div>
          <h2 className="font-display font-extrabold text-3xl sm:text-5xl text-white tracking-tight">
            The Midnight Developer <span className="text-phantom-mint text-glow-mint">Manifesto</span>
          </h2>
          <p className="text-slate-400 text-sm sm:text-base font-mono">
            Vũ trụ kỳ bí của Ma Cà Tưng: Biến cà phê nửa đêm thành những dòng mã hoàn mỹ.
          </p>
        </div>

        {/* Developer Stats Grid */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6 mb-16">
          {developerStats.map((stat) => (
            <div
              key={stat.label}
              onMouseEnter={() => sound.playTerminalKey()}
              className="p-6 rounded-2xl glass-panel border border-slate-800 hover-card-glow flex flex-col justify-between group"
            >
              <div className="flex items-center justify-between mb-4">
                <div className="p-2.5 rounded-xl bg-slate-900 border border-slate-700/80 group-hover:border-emerald-500/50 transition-colors">
                  {statIcons[stat.iconName]}
                </div>
                {stat.unit && (
                  <span className="text-[11px] font-mono font-bold text-slate-500 uppercase px-2 py-0.5 rounded bg-slate-900/50">
                    {stat.unit}
                  </span>
                )}
              </div>
              <div>
                <h3 className="text-2xl sm:text-3xl font-display font-bold text-white group-hover:text-phantom-mint transition-colors">
                  {stat.value}
                </h3>
                <p className="text-xs font-mono font-semibold text-slate-300 mt-1">{stat.label}</p>
                <p className="text-[11px] text-slate-500 mt-1">{stat.description}</p>
              </div>
            </div>
          ))}
        </div>

        {/* Tabbed Interactive Philosophy Container */}
        <div className="rounded-3xl glass-panel-glow border border-slate-800 p-6 sm:p-8">
          
          {/* Tabs */}
          <div className="flex flex-wrap items-center gap-2 border-b border-slate-800 pb-4 mb-8">
            <button
              onClick={() => {
                setActiveTab('manifesto');
                sound.playClick();
              }}
              className={`px-4 py-2 rounded-xl text-xs sm:text-sm font-mono font-semibold transition-all flex items-center gap-2 ${
                activeTab === 'manifesto'
                  ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 shadow-glow-mint'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Moon className="w-4 h-4" />
              <span>1. Triết Lý 00:00 AM</span>
            </button>

            <button
              onClick={() => {
                setActiveTab('day_vs_night');
                sound.playClick();
              }}
              className={`px-4 py-2 rounded-xl text-xs sm:text-sm font-mono font-semibold transition-all flex items-center gap-2 ${
                activeTab === 'day_vs_night'
                  ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Sun className="w-4 h-4" />
              <span>2. Day vs Midnight Mode</span>
            </button>

            <button
              onClick={() => {
                setActiveTab('values');
                sound.playClick();
              }}
              className={`px-4 py-2 rounded-xl text-xs sm:text-sm font-mono font-semibold transition-all flex items-center gap-2 ${
                activeTab === 'values'
                  ? 'bg-purple-500/20 text-purple-300 border border-purple-500/40'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Code className="w-4 h-4" />
              <span>3. Khắc Bùa Chất Lượng</span>
            </button>
          </div>

          {/* Tab 1: Manifesto */}
          {activeTab === 'manifesto' && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center animate-fadeIn">
              <div className="space-y-4">
                <h3 className="font-display font-bold text-2xl text-white flex items-center gap-2">
                  <span>Tại sao lại là</span>
                  <span className="text-talisman-yellow italic">"Code at midnight"?</span>
                </h3>
                <p className="text-slate-300 text-sm sm:text-base leading-relaxed">
                  Khi đồng hồ điểm 12 giờ đêm, thế giới xung quanh dần chìm vào giấc ngủ. Tiếng thông báo tắt lịm, không còn những cuộc họp bất chợt hay tin nhắn gián đoạn. Đó là khoảnh khắc vàng để trí tuệ đạt trạng thái <strong>Deep Flow</strong> — nơi mọi bài toán hóc búa nhất về kiến trúc hệ thống và UI/UX được giải quyết chỉ sau một ngụm cà phê.
                </p>
                <p className="text-slate-300 text-sm sm:text-base leading-relaxed">
                  Giống như chú <strong>Ma Cà Tưng</strong> năng động với lá bùa trên trán, tôi biến từng đêm thành một buổi luyện kim mã nguồn: viết code tinh gọn, tối ưu từng mili-giây, và tạo ra những sản phẩm mang lại niềm hứng khởi bất tận cho người dùng.
                </p>
              </div>

              <div className="p-6 rounded-2xl bg-midnight-900/90 border border-slate-800 font-mono text-xs text-slate-300 space-y-2">
                <div className="flex items-center justify-between text-slate-500 border-b border-slate-800 pb-2">
                  <span>// midnight_protocol.ts</span>
                  <span className="text-emerald-400">● RUNNING</span>
                </div>
                <pre className="text-emerald-300 leading-relaxed overflow-x-auto">
{`const midnightProtocol = async () => {
  const world = await Universe.sleep();
  const coffee = RobustaDark.brew({ temp: 92, strength: 'MAX' });
  
  while (isNight && coffee.level > 0) {
    const feature = await Architect.craft({
      quality: 'PIXEL_PERFECT',
      latency: 'SUB_MILLISECOND',
      tests: '100% COVERAGE',
      bugs: 0
    });
    
    await Git.push({ branch: 'production', safe: true });
    console.log('⚡ Shipped at 03:30 AM with 0 bugs!');
  }
};`}
                </pre>
              </div>
            </div>
          )}

          {/* Tab 2: Day vs Night Mode Comparison */}
          {activeTab === 'day_vs_night' && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 animate-fadeIn">
              {/* Daytime */}
              <div className="p-6 rounded-2xl bg-slate-900/60 border border-amber-500/20 space-y-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-amber-400 font-bold font-mono text-sm">
                    <Sun className="w-4 h-4" />
                    <span>BAN NGÀY (DAYLIGHT REALM)</span>
                  </div>
                  <span className="text-xs font-mono text-slate-500">09:00 - 17:00</span>
                </div>
                <ul className="space-y-2.5 text-xs sm:text-sm text-slate-400 font-mono">
                  <li className="flex items-start gap-2">
                    <span className="text-rose-400">✕</span>
                    <span>14 cuộc họp ngắn "sync 5 phút" kéo dài 45 phút</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-rose-400">✕</span>
                    <span>68 tin nhắn Slack / Teams hỏi "Ủa sao tính năng này..."</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-rose-400">✕</span>
                    <span>Context switching liên tục, khó tập trung suy nghĩ sâu</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-rose-400">✕</span>
                    <span>Hiệu suất lập trình thực tế: ~35%</span>
                  </li>
                </ul>
              </div>

              {/* Midnight Mode */}
              <div className="p-6 rounded-2xl bg-midnight-900 border border-emerald-500/40 shadow-glow-mint space-y-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-emerald-300 font-bold font-mono text-sm">
                    <Moon className="w-4 h-4 text-talisman-yellow" />
                    <span>NỬA ĐÊM (MIDNIGHT MODE)</span>
                  </div>
                  <span className="text-xs font-mono text-emerald-400 font-bold">00:00 - 05:00</span>
                </div>
                <ul className="space-y-2.5 text-xs sm:text-sm text-slate-200 font-mono">
                  <li className="flex items-start gap-2">
                    <span className="text-emerald-400 font-bold">✓</span>
                    <span>0 cuộc họp, 0 gián đoạn, hoàn toàn tĩnh lặng</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-emerald-400 font-bold">✓</span>
                    <span>1 cốc cà phê Robusta đậm đặc + playlist Lofi / Synthwave</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-emerald-400 font-bold">✓</span>
                    <span>Deep Flow State: Giải quyết xong module phức tạp trong 2 tiếng</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-emerald-400 font-bold">✓</span>
                    <span>Hiệu suất lập trình: 1000% bứt phá</span>
                  </li>
                </ul>
              </div>
            </div>
          )}

          {/* Tab 3: Core Values */}
          {activeTab === 'values' && (
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 animate-fadeIn">
              <div className="p-5 rounded-2xl bg-midnight-900/80 border border-slate-800 space-y-3">
                <div className="w-10 h-10 rounded-xl bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
                  <Shield className="w-5 h-5" />
                </div>
                <h4 className="font-display font-bold text-white text-base">Type Safety & Resilience</h4>
                <p className="text-xs text-slate-400 leading-relaxed font-mono">
                  Không để bug lọt vào production. TypeScript nghiêm ngặt, unit tests chặt chẽ và error handling chuẩn xác như bùa trừ tà.
                </p>
              </div>

              <div className="p-5 rounded-2xl bg-midnight-900/80 border border-slate-800 space-y-3">
                <div className="w-10 h-10 rounded-xl bg-cyan-500/10 border border-cyan-500/30 flex items-center justify-center text-cyan-400">
                  <Zap className="w-5 h-5" />
                </div>
                <h4 className="font-display font-bold text-white text-base">Sub-millisecond Speed</h4>
                <p className="text-xs text-slate-400 leading-relaxed font-mono">
                  Tối ưu hóa từng byte dữ liệu. Render 60 FPS mượt mà, cold-start dưới 20ms, cấu trúc dữ liệu không lãng phí bộ nhớ.
                </p>
              </div>

              <div className="p-5 rounded-2xl bg-midnight-900/80 border border-slate-800 space-y-3">
                <div className="w-10 h-10 rounded-xl bg-amber-500/10 border border-amber-500/30 flex items-center justify-center text-amber-400">
                  <Sparkles className="w-5 h-5" />
                </div>
                <h4 className="font-display font-bold text-white text-base">Bespoke Aesthetics</h4>
                <p className="text-xs text-slate-400 leading-relaxed font-mono">
                  Giao diện không nhàm chán. Tỉ mỉ từng vi chuyển động (micro-animations), âm thanh tương tác và trải nghiệm người dùng quyến rũ.
                </p>
              </div>
            </div>
          )}

        </div>

      </div>
    </section>
  );
};
