// src/components/projects/ProjectsSection.tsx
import React, { useState } from 'react';
import { projectsData } from '../../data/projectsData';
import type { Project } from '../../types/portfolio';
import { ProjectModal } from './ProjectModal';
import { sound } from '../../audio/soundEffects';
import { Sparkles, ExternalLink, Eye, Layers } from 'lucide-react';
import { GithubIcon } from '../ui/Icons';

export const ProjectsSection: React.FC = () => {
  const [activeCategory, setActiveCategory] = useState<string>('all');
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);

  const categories = [
    { id: 'all', label: 'All Artifacts' },
    { id: 'fullstack', label: 'Full-Stack Systems' },
    { id: 'creative', label: 'Creative UI / Web Audio' },
    { id: 'ai-web3', label: 'AI & Web3 Protocols' },
    { id: 'tools', label: 'Developer Tooling' },
  ];

  const filteredProjects = activeCategory === 'all'
    ? projectsData
    : projectsData.filter((p) => p.category === activeCategory);

  const handleOpenProject = (project: Project) => {
    sound.playTalisman();
    setSelectedProject(project);
  };

  return (
    <section id="projects" className="py-24 relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-12">
          <div className="space-y-3">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full glass-panel border border-slate-700 text-xs font-mono text-emerald-300">
              <Layers className="w-3.5 h-3.5 text-talisman-yellow" />
              <span>// ARTIFACTS & SYSTEMS</span>
            </div>
            <h2 className="font-display font-extrabold text-3xl sm:text-5xl text-white tracking-tight">
              The Midnight <span className="text-phantom-mint text-glow-mint">Grimoire</span>
            </h2>
            <p className="text-slate-400 font-mono text-sm sm:text-base max-w-xl">
              Những kiệt tác phần mềm và sản phẩm mã nguồn được đúc kết dưới ánh trăng nửa đêm.
            </p>
          </div>

          {/* Category Filter Pills */}
          <div className="flex flex-wrap gap-1.5 p-1 rounded-2xl glass-panel border border-slate-800">
            {categories.map((cat) => (
              <button
                key={cat.id}
                onClick={() => {
                  sound.playClick();
                  setActiveCategory(cat.id);
                }}
                className={`px-3.5 py-1.5 rounded-xl text-xs font-mono font-medium transition-all ${
                  activeCategory === cat.id
                    ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 shadow-glow-mint'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                {cat.label}
              </button>
            ))}
          </div>
        </div>

        {/* Projects Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredProjects.map((project) => (
            <div
              key={project.id}
              className="rounded-3xl glass-panel border border-slate-800/80 hover:border-emerald-500/40 hover-card-glow flex flex-col justify-between overflow-hidden group transition-all duration-300"
            >
              <div>
                {/* Project Header Banner */}
                <div
                  className={`h-40 p-6 bg-gradient-to-br ${project.coverGradient} relative flex flex-col justify-between overflow-hidden`}
                >
                  <div className="flex items-center justify-between z-10">
                    <span className="px-2.5 py-0.5 rounded-md bg-black/50 backdrop-blur-sm text-[11px] font-mono uppercase tracking-wider text-emerald-300 border border-emerald-500/30">
                      {project.category}
                    </span>
                    {project.featured && (
                      <span className="px-2 py-0.5 rounded-md bg-talisman-yellow/20 backdrop-blur-sm text-[10px] font-mono uppercase font-bold text-talisman-yellow border border-talisman-yellow/40 flex items-center gap-1">
                        <Sparkles className="w-3 h-3" /> Featured
                      </span>
                    )}
                  </div>

                  <div className="z-10">
                    <h3 className="font-display font-bold text-xl text-white group-hover:text-phantom-mint transition-colors">
                      {project.title}
                    </h3>
                  </div>

                  {/* Corner Talisman Rune watermark */}
                  <div className="absolute -bottom-4 -right-4 font-mono text-5xl font-extrabold text-white/5 select-none pointer-events-none">
                    0xMID
                  </div>
                </div>

                {/* Content */}
                <div className="p-6 space-y-4">
                  <p className="text-slate-300 text-xs sm:text-sm line-clamp-3 leading-relaxed">
                    {project.description}
                  </p>

                  {/* Metrics snippet */}
                  <div className="grid grid-cols-3 gap-2 py-2 border-y border-slate-800/80">
                    {project.metrics.map((m, idx) => (
                      <div key={idx} className="text-center">
                        <div className="text-xs font-display font-bold text-phantom-mint">{m.value}</div>
                        <div className="text-[10px] font-mono text-slate-500 truncate">{m.label}</div>
                      </div>
                    ))}
                  </div>

                  {/* Tech stack badges */}
                  <div className="flex flex-wrap gap-1.5">
                    {project.tags.slice(0, 4).map((tag) => (
                      <span
                        key={tag}
                        className="px-2 py-0.5 rounded-md bg-slate-900 border border-slate-800 text-[11px] font-mono text-slate-400"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              {/* Card Footer Actions */}
              <div className="p-6 pt-0 flex items-center justify-between border-t border-slate-800/60 mt-4">
                <button
                  onClick={() => handleOpenProject(project)}
                  className="text-xs font-mono text-emerald-300 hover:text-emerald-200 font-bold flex items-center gap-1.5 group-hover:translate-x-1 transition-transform"
                >
                  <Eye className="w-3.5 h-3.5" />
                  <span>Inspect Details →</span>
                </button>

                <div className="flex items-center gap-2">
                  {project.githubUrl && (
                    <a
                      href={project.githubUrl}
                      target="_blank"
                      rel="noreferrer"
                      onClick={(e) => {
                        e.stopPropagation();
                        sound.playClick();
                      }}
                      className="p-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
                      title="GitHub"
                    >
                      <GithubIcon className="w-3.5 h-3.5" />
                    </a>
                  )}
                  {project.liveUrl && (
                    <a
                      href={project.liveUrl}
                      target="_blank"
                      rel="noreferrer"
                      onClick={(e) => {
                        e.stopPropagation();
                        sound.playClick();
                      }}
                      className="p-2 rounded-xl bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-300 transition-colors"
                      title="Live Demo"
                    >
                      <ExternalLink className="w-3.5 h-3.5" />
                    </a>
                  )}
                </div>
              </div>

            </div>
          ))}
        </div>

      </div>

      {/* Modal Popup */}
      <ProjectModal
        project={selectedProject}
        onClose={() => setSelectedProject(null)}
      />
    </section>
  );
};

// resources/js/Components/projects/ProjectsSection.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { projectsData } from '@/data/projectsData';
import type { Project } from '@/types/portfolio';
import ProjectModal from './ProjectModal.vue';
import { sound } from '@/audio/soundEffects';
import Icons from '@/Components/ui/Icons.vue';

interface Props {
  projects?: Project[];
}

const props = withDefaults(defineProps<Props>(), {
  projects: () => [],
});

type CategoryFilter = 'all' | 'fullstack' | 'creative' | 'ai-web3' | 'tools';

const activeCategory = ref<CategoryFilter>('all');
const selectedProject = ref<Project | null>(null);
const isModalOpen = ref(false);

const categories = [
  { id: 'all', label: 'Tất Cả Dự Án' },
  { id: 'fullstack', label: 'Full-Stack' },
  { id: 'creative', label: 'Creative UI & Audio' },
  { id: 'ai-web3', label: 'AI & Microservices' },
  { id: 'tools', label: 'Developer Tools' }
] as const;

const allProjects = computed(() => {
  return props.projects && props.projects.length > 0 ? props.projects : projectsData;
});

const filteredProjects = computed(() => {
  if (activeCategory.value === 'all') return allProjects.value;
  return allProjects.value.filter((p) => p.category === activeCategory.value);
});

const setCategory = (cat: CategoryFilter) => {
  activeCategory.value = cat;
  sound.playClick();
};

const openProject = (project: Project) => {
  selectedProject.value = project;
  isModalOpen.value = true;
  sound.playClick();
};

const closeModal = () => {
  isModalOpen.value = false;
  selectedProject.value = null;
  sound.playClick();
};
</script>

<template>
  <section id="projects" class="scroll-mt-24 w-full py-16 sm:py-20 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-left">
    <!-- Header -->
    <div class="flex flex-col items-start mb-10">
      <span class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-phantom-mint text-xs font-mono mb-3 whitespace-nowrap select-none">
        📜 The Grimoire Portfolio
      </span>
      <h2 class="text-3xl sm:text-4xl lg:text-5xl font-display font-extrabold text-white tracking-tight">
        Tác Phẩm & <span class="text-phantom-mint">Dự Án Thực Chiến</span>
      </h2>
      <p class="text-sm sm:text-base text-slate-400 mt-2 max-w-2xl font-sans">
        Những hệ thống phân tán, web app tải cao và công cụ sáng tạo được kiến tạo trong những phiên lập trình tĩnh lặng.
      </p>
    </div>

    <!-- Category Filter Tabs -->
    <div class="flex items-center gap-2 mb-8 overflow-x-auto no-scrollbar pb-2">
      <button
        v-for="cat in categories"
        :key="cat.id"
        type="button"
        class="px-3.5 py-2 rounded-xl text-xs sm:text-sm font-mono font-medium transition-all min-h-[40px] shrink-0 border select-none whitespace-nowrap"
        :class="activeCategory === cat.id
          ? 'bg-phantom-mint text-midnight-950 border-phantom-mint font-bold shadow-glow-mint'
          : 'bg-midnight-900/80 text-slate-400 border-white/5 hover:border-white/20 hover:text-white'"
        @click="setCategory(cat.id as CategoryFilter)"
      >
        {{ cat.label }}
      </button>
    </div>

    <!-- Project Cards Grid -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <div
        v-for="project in filteredProjects"
        :key="project.id"
        class="rounded-2xl border border-white/[0.07] glass-panel overflow-hidden flex flex-col justify-between transition-all duration-300 hover:-translate-y-1 hover:border-phantom-mint/40 group"
      >
        <!-- Card Cover Banner (Minimalist Deep Dark Header) -->
        <div class="p-5 pb-3 border-b border-white/5 flex flex-col justify-between bg-midnight-900/60">
          <div class="flex items-center justify-between mb-3">
            <span class="px-2.5 py-0.5 rounded-full bg-white/5 text-[10px] font-mono uppercase tracking-wider text-slate-300 border border-white/10 whitespace-nowrap">
              {{ project.category }}
            </span>
            <span v-if="project.featured" class="text-[11px] font-mono text-talisman-gold bg-amber-500/10 px-2 py-0.5 rounded-full border border-talisman-gold/30 whitespace-nowrap">
              ★ Featured
            </span>
          </div>
          <h3 class="font-display font-bold text-lg text-white group-hover:text-phantom-mint transition-colors">
            {{ project.title }}
          </h3>
          <p class="text-xs font-mono text-phantom-mint mt-1 truncate">{{ project.tagline }}</p>
        </div>

        <!-- Card Content -->
        <div class="p-5 flex-1 flex flex-col justify-between text-left">
          <div>
            <p class="text-xs text-slate-400 line-clamp-2 mb-4 leading-relaxed font-sans">{{ project.description }}</p>

            <!-- Metrics Preview -->
            <div class="grid grid-cols-3 gap-2 p-2.5 rounded-xl bg-midnight-950/80 border border-white/5 mb-4">
              <div v-for="m in project.metrics" :key="m.label" class="text-center">
                <div class="text-[10px] font-mono text-slate-500 truncate">{{ m.label }}</div>
                <div class="text-xs font-display font-bold text-slate-200 mt-0.5 whitespace-nowrap">{{ m.value }}</div>
              </div>
            </div>

            <!-- Tech Stack Badges -->
            <div class="flex flex-wrap gap-1.5 mb-5">
              <span
                v-for="tech in project.tags.slice(0, 4)"
                :key="tech"
                class="px-2 py-0.5 rounded text-[10px] font-mono bg-white/5 text-slate-300 border border-white/5 whitespace-nowrap"
              >
                {{ tech }}
              </span>
            </div>
          </div>

          <!-- Actions -->
          <div class="flex items-center gap-2 pt-2 border-t border-white/5">
            <button
              type="button"
              class="flex-1 py-2.5 px-3 rounded-xl bg-white/5 hover:bg-phantom-mint text-slate-200 hover:text-midnight-950 font-display font-bold text-xs transition-all min-h-[40px] flex items-center justify-center gap-1 whitespace-nowrap border border-white/10 hover:border-phantom-mint"
              @click="openProject(project)"
            >
              <span>Xem Chi Tiết</span>
              <span>→</span>
            </button>
            <a
              v-if="project.githubUrl"
              :href="project.githubUrl"
              target="_blank"
              rel="noopener noreferrer"
              class="p-2.5 rounded-xl bg-midnight-900 border border-white/10 hover:border-white/30 text-slate-300 hover:text-white transition-all min-h-[40px] min-w-[40px] flex items-center justify-center text-xs font-mono"
              title="Mã nguồn GitHub"
            >
              <Icons name="Github" :size="16" />
            </a>
          </div>
        </div>
      </div>
    </div>

    <!-- Project Modal Dialog -->
    <ProjectModal
      :is-open="isModalOpen"
      :project="selectedProject"
      @close="closeModal"
    />
  </section>
</template>
