// resources/js/Components/experience/ExperienceSection.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { experienceData } from '@/data/experienceData';
import { sound } from '@/audio/soundEffects';
import { useI18n } from '@/composables/useI18n';

interface ExperienceRecord {
  id: number | string;
  role: string;
  company: string;
  period: string;
  type: string;
  location: string;
  summary: string;
  achievements?: string[];
  technologies?: string[];
  midnightQuest?: string;
}

interface Props {
  experiences?: ExperienceRecord[];
}

const props = withDefaults(defineProps<Props>(), {
  experiences: () => [],
});
const { t } = useI18n();

const activeType = ref<string>('all');

const types = [
  { id: 'all', label: 'All milestones' },
  { id: 'Full-time', label: 'Full-Time' },
  { id: 'Contract', label: 'Contract & Creative' },
  { id: 'Open Source', label: 'Indie & Open Source' },
];

const typeLabel = (id: string) => ({ all: t('experience.all'), Contract: t('experience.contract'), 'Open Source': t('experience.openSource') }[id] || id);

const allExperiences = computed(() => {
  if (props.experiences && props.experiences.length > 0) {
    return props.experiences;
  }
  return experienceData;
});

const displayExperiences = computed(() => {
  if (activeType.value === 'all') return allExperiences.value;
  return allExperiences.value.filter((e) => e.type.toLowerCase().includes(activeType.value.toLowerCase()));
});

const setType = (typeId: string) => {
  activeType.value = typeId;
  sound.playClick();
};
</script>

<template>
  <section id="experience" class="scroll-mt-24 w-full py-16 sm:py-20 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-left">
    <!-- Header -->
    <div class="flex flex-col lg:flex-row lg:items-end justify-between gap-6 mb-10">
      <div class="flex flex-col items-start">
        <span class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-phantom-mint text-xs font-mono mb-3 whitespace-nowrap select-none shadow-glow-mint">
          📜 {{ t('experience.badge') }}
        </span>
        <h2 class="text-3xl sm:text-4xl lg:text-5xl font-display font-extrabold text-white tracking-tight">
          {{ t('experience.title') }} <span class="text-transparent bg-clip-text bg-gradient-to-r from-phantom-mint via-phantom-cyan to-talisman-gold">{{ t('experience.titleAccent') }}</span>
        </h2>
        <p class="text-sm sm:text-base text-slate-400 mt-2 max-w-2xl font-sans">
          {{ t('experience.description') }}
        </p>
      </div>

      <!-- Filter Types -->
      <div class="flex items-center gap-2 overflow-x-auto no-scrollbar pb-1">
        <button
          v-for="t in types"
          :key="t.id"
          type="button"
          class="px-3.5 py-2 rounded-xl text-xs font-mono transition-all min-h-[38px] shrink-0 border select-none whitespace-nowrap"
          :class="activeType === t.id
            ? 'bg-phantom-mint text-midnight-950 border-phantom-mint font-bold shadow-glow-mint'
            : 'bg-midnight-900/80 text-slate-400 border-white/5 hover:border-white/20 hover:text-white'"
          @click="setType(t.id)"
        >
          {{ typeLabel(t.id) }}
        </button>
      </div>
    </div>

    <!-- Timeline Container -->
    <div class="relative pl-6 sm:pl-8 space-y-8">
      <!-- Continuous Vertical Connector Line with Gradient -->
      <div class="absolute top-3 bottom-3 left-3 w-[2px] bg-gradient-to-b from-phantom-mint via-phantom-cyan/40 to-transparent" />

      <!-- Timeline Items -->
      <div
        v-for="item in displayExperiences"
        :key="item.id"
        class="relative flex flex-col items-start group"
      >
        <!-- Node Dot Indicator -->
        <div class="absolute -left-[27px] sm:-left-[31px] top-2 w-5 h-5 rounded-full bg-midnight-950 border-2 border-phantom-mint flex items-center justify-center text-phantom-mint shadow-glow-mint z-10 select-none group-hover:scale-125 transition-transform">
          <span class="w-1.5 h-1.5 rounded-full bg-phantom-mint" />
        </div>

        <!-- Experience Card -->
        <div class="w-full glass-panel p-6 sm:p-7 rounded-2xl border border-white/[0.08] hover:border-phantom-mint/30 transition-all duration-300 hover:shadow-xl hover:shadow-black/40 text-left">
          <!-- Period & Type Badges -->
          <div class="flex flex-wrap items-center justify-between gap-2 mb-3">
            <div class="flex items-center gap-2">
              <span class="px-3 py-1 rounded-full bg-phantom-mint/10 text-phantom-mint font-mono text-xs font-bold border border-phantom-mint/30 shadow-glow-mint whitespace-nowrap">
                {{ item.period }}
              </span>
              <span class="px-2.5 py-0.5 rounded-full bg-white/5 text-slate-300 font-mono text-[11px] border border-white/10 whitespace-nowrap">
                {{ item.type }}
              </span>
            </div>
            <span class="text-xs font-mono text-slate-400 whitespace-nowrap flex items-center gap-1">
              <span>📍</span>
              <span>{{ item.location }}</span>
            </span>
          </div>

          <!-- Role & Company -->
          <h3 class="text-lg sm:text-xl font-display font-bold text-white group-hover:text-phantom-mint transition-colors">
            {{ item.role }}
          </h3>
          <div class="text-xs sm:text-sm font-mono text-phantom-mint mt-0.5 font-semibold">
            {{ item.company }}
          </div>

          <!-- Summary -->
          <p class="text-xs sm:text-sm text-slate-300 mt-3 leading-relaxed font-sans">
            {{ item.summary }}
          </p>

          <!-- Key Achievements -->
          <div v-if="item.achievements && item.achievements.length > 0" class="mt-4">
            <ul class="space-y-2 text-xs sm:text-sm text-slate-300 font-sans">
              <li v-for="(ach, i) in item.achievements" :key="i" class="flex items-start gap-2.5">
                <span class="text-phantom-mint mt-0.5 select-none shrink-0 text-xs font-bold">✦</span>
                <span class="leading-relaxed">{{ ach }}</span>
              </li>
            </ul>
          </div>

          <!-- Midnight Quest Story (Lore) -->
          <div
            v-if="item.midnightQuest"
            class="mt-4 p-3.5 rounded-xl bg-amber-950/20 border border-talisman-gold/25 text-xs text-amber-200/90 flex items-start gap-2.5"
          >
            <span class="text-base shrink-0">🌙</span>
            <div>
              <span class="font-mono text-[10px] text-talisman-gold font-bold uppercase tracking-wider block mb-0.5">{{ t('experience.quest') }}</span>
              <p class="leading-relaxed">{{ item.midnightQuest }}</p>
            </div>
          </div>

          <!-- Tech Stack Badges -->
          <div v-if="item.technologies && item.technologies.length > 0" class="flex flex-wrap gap-1.5 mt-4 pt-3 border-t border-white/5">
            <span
              v-for="tech in item.technologies"
              :key="tech"
              class="px-2.5 py-0.5 rounded text-[11px] font-mono bg-white/5 text-slate-300 border border-white/5 whitespace-nowrap hover:border-white/15 transition-colors"
            >
              {{ tech }}
            </span>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

// src/components/experience/ExperienceSection.tsx
import React from 'react';
import { experienceData } from '../../data/experienceData';
import { sound } from '../../audio/soundEffects';
import { Briefcase, MapPin, CheckCircle2, Moon } from 'lucide-react';

export const ExperienceSection: React.FC = () => {
  return (
    <section id="experience" className="py-24 relative border-t border-slate-800/80">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full glass-panel border border-slate-700 text-xs font-mono text-emerald-300">
            <Briefcase className="w-3.5 h-3.5 text-talisman-yellow" />
            <span>// CAREER EXPEDITION</span>
          </div>
          <h2 className="font-display font-extrabold text-3xl sm:text-5xl text-white tracking-tight">
            The Midnight <span className="text-phantom-mint text-glow-mint">Chronicles</span>
          </h2>
          <p className="text-slate-400 font-mono text-sm sm:text-base">
            Hành trình chinh phục các dự án quy mô lớn và giải quyết các bài toán hóc búa nhất.
          </p>
        </div>

        {/* Timeline */}
        <div className="relative border-l-2 border-slate-800 ml-4 sm:ml-32 space-y-12">
          {experienceData.map((item) => (
            <div
              key={item.id}
              onMouseEnter={() => sound.playTerminalKey()}
              className="relative pl-6 sm:pl-10 group"
            >
              {/* Timeline marker icon */}
              <div className="absolute -left-[17px] top-1.5 w-8 h-8 rounded-full bg-midnight-950 border-2 border-emerald-500 flex items-center justify-center shadow-glow-mint group-hover:scale-125 transition-transform">
                <div className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse" />
              </div>

              {/* Period badge for desktop (left aligned) */}
              <div className="hidden sm:block absolute -left-36 top-2 font-mono text-xs text-talisman-yellow font-bold text-right w-24">
                {item.period}
              </div>

              {/* Experience Card */}
              <div className="p-6 sm:p-8 rounded-3xl glass-panel border border-slate-800/80 hover:border-emerald-500/40 hover-card-glow transition-all">
                
                {/* Header inside card */}
                <div className="flex flex-wrap items-center justify-between gap-2 mb-3">
                  <div>
                    {/* Period badge for mobile */}
                    <span className="sm:hidden inline-block font-mono text-xs text-talisman-yellow font-bold mb-1">
                      {item.period}
                    </span>
                    <h3 className="font-display font-bold text-xl sm:text-2xl text-white group-hover:text-phantom-mint transition-colors">
                      {item.role}
                    </h3>
                    <div className="flex flex-wrap items-center gap-3 text-xs font-mono text-slate-400 mt-1">
                      <span className="text-slate-200 font-semibold">{item.company}</span>
                      <span>•</span>
                      <span className="flex items-center gap-1">
                        <MapPin className="w-3 h-3 text-cyan-400" />
                        {item.location}
                      </span>
                    </div>
                  </div>

                  <span className="px-3 py-1 rounded-full text-[11px] font-mono uppercase font-bold bg-emerald-500/10 text-emerald-300 border border-emerald-500/30">
                    {item.type}
                  </span>
                </div>

                {/* Summary */}
                <p className="text-slate-300 text-xs sm:text-sm leading-relaxed mb-4">
                  {item.summary}
                </p>

                {/* Key Achievements */}
                <div className="space-y-2 mb-4">
                  {item.achievements.map((ach, idx) => (
                    <div key={idx} className="flex items-start gap-2.5 text-xs sm:text-sm text-slate-300 font-mono">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400 flex-shrink-0 mt-0.5" />
                      <span>{ach}</span>
                    </div>
                  ))}
                </div>

                {/* Technologies */}
                <div className="flex flex-wrap gap-1.5 mb-4">
                  {item.technologies.map((tech) => (
                    <span
                      key={tech}
                      className="px-2.5 py-0.5 rounded-lg bg-midnight-950 border border-slate-800 text-[11px] font-mono text-slate-400"
                    >
                      {tech}
                    </span>
                  ))}
                </div>

                {/* Midnight Quest Box */}
                <div className="p-3.5 rounded-2xl bg-midnight-950/90 border border-emerald-500/20 flex items-start gap-2.5 text-xs font-mono">
                  <Moon className="w-4 h-4 text-talisman-yellow flex-shrink-0 mt-0.5" />
                  <div>
                    <span className="text-emerald-300 font-bold">Midnight Quest Lore: </span>
                    <span className="text-slate-300">{item.midnightQuest}</span>
                  </div>
                </div>

              </div>
            </div>
          ))}
        </div>

      </div>
    </section>
  );
};
